#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 aufkrawall
# SPDX-License-Identifier: MIT
"""Build script for Green Curve.

Downloads Zig if needed, generates the app icon, compiles resources,
then builds ``greencurve.exe``. Linux cross-builds use a separate source set.
"""

import argparse
import hashlib
import json
import math
import os
import shutil
import struct
import subprocess
import sys
import urllib.request
import tarfile
import zipfile
import zlib

ZIG_VERSION = "0.13.0"

# Platform-dependent Zig download settings
if sys.platform == "win32":
    _ZIG_PLATFORM = "windows"
    _ZIG_ARCHIVE_EXT = ".zip"
    _ZIG_EXE_NAME = "zig.exe"
    _ZIG_SHA256 = "d859994725ef9402381e557c60bb57497215682e355204d754ee3df75ee3c158"
elif sys.platform.startswith("linux"):
    _ZIG_PLATFORM = "linux"
    _ZIG_ARCHIVE_EXT = ".tar.xz"
    _ZIG_EXE_NAME = "zig"
    _ZIG_SHA256 = "d45312e61ebcc48032b77bc4cf7fd6915c11fa16e4aad116b66c9468211230ea"
else:
    print(f"Unsupported build host: {sys.platform}")
    sys.exit(1)

ZIG_URL = f"https://ziglang.org/download/{ZIG_VERSION}/zig-{_ZIG_PLATFORM}-x86_64-{ZIG_VERSION}{_ZIG_ARCHIVE_EXT}"
ZIG_SHA256 = _ZIG_SHA256
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ZIG_DIR = os.path.join(SCRIPT_DIR, "zig")
ZIG_EXE = os.path.join(ZIG_DIR, _ZIG_EXE_NAME)
SOURCE_DIR = os.path.join(SCRIPT_DIR, "source")
BUILD_WORK_DIR = os.path.join(SCRIPT_DIR, "build-tmp")
ZIG_GLOBAL_CACHE_DIR = os.path.join(BUILD_WORK_DIR, "zig-global-cache")
ZIG_LOCAL_CACHE_DIR = os.path.join(BUILD_WORK_DIR, "zig-local-cache")
BUILD_NUMBER_PATH = os.path.join(SCRIPT_DIR, "BUILD_NUMBER")
BUILD_FINGERPRINT_PATH = os.path.join(SCRIPT_DIR, ".build_fingerprint")
WINDOWS_SOURCE_FILES = [
    os.path.join(SOURCE_DIR, "main.cpp"),
    os.path.join(SOURCE_DIR, "app_shared.cpp"),
    os.path.join(SOURCE_DIR, "config_utils.cpp"),
    os.path.join(SOURCE_DIR, "fan_curve.cpp"),
    os.path.join(SOURCE_DIR, "string_table.cpp"),
]
LINUX_SOURCE_FILES = [
    os.path.join(SOURCE_DIR, "linux_main.cpp"),
    os.path.join(SOURCE_DIR, "linux_port.cpp"),
    os.path.join(SOURCE_DIR, "linux_port_profiles.cpp"),
    os.path.join(SOURCE_DIR, "linux_tui.cpp"),
    os.path.join(SOURCE_DIR, "string_table.cpp"),
]
WINDOWS_OUTPUT_EXE = os.path.join(SCRIPT_DIR, "greencurve.exe")
WINDOWS_TEMP_OUTPUT_EXE = WINDOWS_OUTPUT_EXE + ".new"
WINDOWS_BACKUP_EXE = WINDOWS_OUTPUT_EXE + ".bak"
WINDOWS_SERVICE_OUTPUT_EXE = os.path.join(SCRIPT_DIR, "greencurve-service.exe")
WINDOWS_SERVICE_TEMP_OUTPUT_EXE = WINDOWS_SERVICE_OUTPUT_EXE + ".new"
WINDOWS_SERVICE_BACKUP_EXE = WINDOWS_SERVICE_OUTPUT_EXE + ".bak"
LINUX_TARGET = "x86_64-linux-musl"
LINUX_OUTPUT_BIN = os.path.join(SCRIPT_DIR, f"greencurve-{LINUX_TARGET}")
LINUX_TEMP_OUTPUT_BIN = LINUX_OUTPUT_BIN + ".new"
LINUX_BACKUP_BIN = LINUX_OUTPUT_BIN + ".bak"
ICON_ICO = os.path.join(SCRIPT_DIR, "greencurve.ico")
TRAY_ICON_DEFAULT_ICO = os.path.join(SCRIPT_DIR, "greencurve_tray_default.ico")
TRAY_ICON_OC_ICO = os.path.join(SCRIPT_DIR, "greencurve_tray_oc.ico")
TRAY_ICON_FAN_ICO = os.path.join(SCRIPT_DIR, "greencurve_tray_fan.ico")
TRAY_ICON_OC_FAN_ICO = os.path.join(SCRIPT_DIR, "greencurve_tray_oc_fan.ico")
ICON_RC = os.path.join(SCRIPT_DIR, "icon.rc")
ICON_RES = os.path.join(SCRIPT_DIR, "icon.res")

os.makedirs(ZIG_GLOBAL_CACHE_DIR, exist_ok=True)
os.makedirs(ZIG_LOCAL_CACHE_DIR, exist_ok=True)
os.environ.setdefault("ZIG_GLOBAL_CACHE_DIR", ZIG_GLOBAL_CACHE_DIR)
os.environ.setdefault("ZIG_LOCAL_CACHE_DIR", ZIG_LOCAL_CACHE_DIR)

ICON_OUTPUTS = [
    ("app", ICON_ICO, (256, 128, 64, 48, 32, 24, 16)),
    ("tray_default", TRAY_ICON_DEFAULT_ICO, (64, 48, 32, 24, 16)),
    ("tray_oc", TRAY_ICON_OC_ICO, (64, 48, 32, 24, 16)),
    ("tray_fan", TRAY_ICON_FAN_ICO, (64, 48, 32, 24, 16)),
    ("tray_oc_fan", TRAY_ICON_OC_FAN_ICO, (64, 48, 32, 24, 16)),
]

ICON_RC_CONTENT = """// Generated by build.py. Do not edit by hand.
101 ICON "greencurve.ico"
111 ICON "greencurve_tray_default.ico"
112 ICON "greencurve_tray_oc.ico"
113 ICON "greencurve_tray_fan.ico"
114 ICON "greencurve_tray_oc_fan.ico"
"""

COMMON_FLAGS = [
    "-std=c++17",
    "-Oz",
    "-DNDEBUG",
    "-fno-exceptions",
    "-fno-rtti",
    "-fstack-protector-strong",
    "-ffunction-sections",
    "-fdata-sections",
    f"-I{SOURCE_DIR}",
    "-Wl,--gc-sections",
    "-Wall",
    "-Wextra",
    "-Wshadow",
    "-Wformat=2",
    "-Wnull-dereference",
    "-Wundef",
    "-Wno-unused-function",
    "-Wno-unused-parameter",
    "-Werror",
    "-D_FORTIFY_SOURCE=2",
]

# C-002: read VERSION and inject it into all compile commands
APP_VERSION = "0.12"
APP_BUILD_NUMBER = 0
_version_path = os.path.join(SCRIPT_DIR, "VERSION")
if os.path.exists(_version_path):
    with open(_version_path, "r", encoding="utf-8") as _vf:
        APP_VERSION = _vf.read().strip()

SANITIZER_FLAGS = [
    "-fsanitize=undefined",
    "-fno-sanitize-recover=all",
    "-g",
]

WINDOWS_FLAGS = [
    "-Wl,--subsystem,windows,--dynamicbase,--nxcompat,--high-entropy-va",
    "-s",
]

LINUX_FLAGS = [
    "-target",
    LINUX_TARGET,
    "-static",
    "-fPIE",
    "-pie",
    "-Wl,-z,relro,-z,now",
    "-Wl,-z,noexecstack",
    "-s",
    "-fstack-protector-strong",
]

WINDOWS_LINK_LIBS = [
    "-luser32",
    "-lgdi32",
    "-ladvapi32",
    "-lshell32",
    "-lole32",
    "-lwtsapi32",
]

WINDOWS_SERVICE_LINK_LIBS = [
    "-lgdi32",
    "-ladvapi32",
    "-lshell32",
    "-lole32",
    "-lwtsapi32",
    "-luserenv",
]


def read_int_file(path, default=0):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read().strip()
        return int(text) if text else default
    except (OSError, ValueError):
        return default


def write_text_if_changed(path, text):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            if handle.read() == text:
                return
    except OSError:
        pass
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def iter_build_fingerprint_inputs():
    for name in ("build.py", "VERSION"):
        path = os.path.join(SCRIPT_DIR, name)
        if os.path.exists(path):
            yield path
    for root, _dirs, files in os.walk(SOURCE_DIR):
        for name in sorted(files):
            if name.endswith((".cpp", ".h")):
                yield os.path.join(root, name)


def compute_build_fingerprint():
    digest = hashlib.sha256()
    for path in sorted(iter_build_fingerprint_inputs()):
        rel = os.path.relpath(path, SCRIPT_DIR).replace("\\", "/")
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        with open(path, "rb") as handle:
            for chunk in iter(lambda: handle.read(65536), b""):
                digest.update(chunk)
        digest.update(b"\0")
    return digest.hexdigest()


def configure_build_number(bump_for_real_build):
    global APP_BUILD_NUMBER
    APP_BUILD_NUMBER = read_int_file(BUILD_NUMBER_PATH, 0)
    fingerprint = compute_build_fingerprint()
    previous = ""
    try:
        with open(BUILD_FINGERPRINT_PATH, "r", encoding="utf-8") as handle:
            previous = handle.read().strip()
    except OSError:
        previous = ""
    if bump_for_real_build and fingerprint != previous:
        APP_BUILD_NUMBER += 1
        write_text_if_changed(BUILD_NUMBER_PATH, f"{APP_BUILD_NUMBER}\n")
        write_text_if_changed(BUILD_FINGERPRINT_PATH, f"{fingerprint}\n")
        print(f"Build number bumped to {APP_BUILD_NUMBER}")
    elif bump_for_real_build and not os.path.exists(BUILD_FINGERPRINT_PATH):
        write_text_if_changed(BUILD_FINGERPRINT_PATH, f"{fingerprint}\n")
    COMMON_FLAGS.append(f'-DAPP_VERSION="\\"{APP_VERSION}\\""')
    COMMON_FLAGS.append(f"-DAPP_BUILD_NUMBER={APP_BUILD_NUMBER}")


def clamp01(value):
    if value < 0.0:
        return 0.0
    if value > 1.0:
        return 1.0
    return value


def clamp255(value):
    return max(0, min(255, int(value + 0.5)))


def lerp(a, b, t):
    return a + (b - a) * t


def lerp_color(a, b, t):
    return (
        lerp(a[0], b[0], t),
        lerp(a[1], b[1], t),
        lerp(a[2], b[2], t),
    )


def composite(dst, src):
    sr, sg, sb, sa = src
    dr, dg, db, da = dst
    src_a = sa / 255.0
    dst_a = da / 255.0
    out_a = src_a + dst_a * (1.0 - src_a)
    if out_a <= 0.0:
        return (0, 0, 0, 0)
    out_r = (sr * src_a + dr * dst_a * (1.0 - src_a)) / out_a
    out_g = (sg * src_a + dg * dst_a * (1.0 - src_a)) / out_a
    out_b = (sb * src_a + db * dst_a * (1.0 - src_a)) / out_a
    return (
        clamp255(out_r),
        clamp255(out_g),
        clamp255(out_b),
        clamp255(out_a * 255.0),
    )


def band_alpha(distance, target, half_width, feather):
    return clamp01((half_width + feather - abs(distance - target)) / feather)


def rounded_rect_distance(px, py, cx, cy, half_w, half_h, radius):
    qx = abs(px - cx) - half_w + radius
    qy = abs(py - cy) - half_h + radius
    ox = max(qx, 0.0)
    oy = max(qy, 0.0)
    outside = math.hypot(ox, oy)
    inside = min(max(qx, qy), 0.0)
    return outside + inside - radius


def point_segment_distance(px, py, ax, ay, bx, by):
    vx = bx - ax
    vy = by - ay
    wx = px - ax
    wy = py - ay
    vv = vx * vx + vy * vy
    if vv <= 1e-6:
        return math.hypot(wx, wy)
    t = (wx * vx + wy * vy) / vv
    t = clamp01(t)
    qx = ax + vx * t
    qy = ay + vy * t
    return math.hypot(px - qx, py - qy)


ICON_STYLES = {
    "app": {
        "bg_top": (8.0, 24.0, 18.0),
        "bg_bottom": (28.0, 76.0, 52.0),
        "glow": (18.0, 26.0, 10.0),
        "border": (108, 216, 164),
        "ring": (28, 178, 110),
        "arc": (198, 255, 226),
        "curve": (232, 255, 242),
        "node": (232, 255, 242),
        "badge": None,
    },
    "tray_default": {
        "bg_top": (8.0, 24.0, 18.0),
        "bg_bottom": (28.0, 76.0, 52.0),
        "glow": (18.0, 26.0, 10.0),
        "border": (108, 216, 164),
        "ring": (28, 178, 110),
        "arc": (198, 255, 226),
        "curve": (232, 255, 242),
        "node": (232, 255, 242),
        "badge": None,
    },
    "tray_oc": {
        "bg_top": (18.0, 18.0, 12.0),
        "bg_bottom": (72.0, 44.0, 18.0),
        "glow": (34.0, 18.0, 6.0),
        "border": (246, 184, 88),
        "ring": (228, 136, 42),
        "arc": (255, 233, 182),
        "curve": (255, 247, 228),
        "node": (255, 247, 228),
        "badge": "diamond",
        "badge_primary": (255, 176, 64),
        "badge_secondary": (255, 233, 182),
    },
    "tray_fan": {
        "bg_top": (8.0, 18.0, 24.0),
        "bg_bottom": (18.0, 54.0, 80.0),
        "glow": (10.0, 18.0, 34.0),
        "border": (110, 220, 240),
        "ring": (44, 176, 220),
        "arc": (210, 248, 255),
        "curve": (230, 251, 255),
        "node": (230, 251, 255),
        "badge": "circle",
        "badge_primary": (94, 226, 255),
        "badge_secondary": (210, 248, 255),
    },
    "tray_oc_fan": {
        "bg_top": (12.0, 18.0, 18.0),
        "bg_bottom": (44.0, 62.0, 54.0),
        "glow": (14.0, 24.0, 20.0),
        "border": (188, 228, 196),
        "ring": (132, 198, 168),
        "arc": (238, 255, 245),
        "curve": (245, 255, 250),
        "node": (245, 255, 250),
        "badge": "split",
        "badge_primary": (255, 176, 64),
        "badge_secondary": (94, 226, 255),
    },
}


def png_chunk(tag, data):
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def rgba_to_png(rgba, size):
    raw = bytearray()
    stride = size * 4
    for y in range(size):
        raw.append(0)
        start = y * stride
        raw.extend(rgba[start : start + stride])
    compressed = zlib.compress(bytes(raw), 9)
    return b"".join(
        [
            b"\x89PNG\r\n\x1a\n",
            png_chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)),
            png_chunk(b"IDAT", compressed),
            png_chunk(b"IEND", b""),
        ]
    )


def render_icon(size, variant="app"):
    style = ICON_STYLES[variant]
    scale = size / 256.0
    center = size * 0.5
    margin = 18.0 * scale
    radius = 52.0 * scale
    ring_radius = 84.0 * scale
    ring_half_width = max(1.2, 8.0 * scale)
    curve_half_width = max(1.3, 6.0 * scale)
    node_radius = max(1.8, 7.0 * scale)
    border_width = max(1.2, 2.6 * scale)
    glow_x = 88.0 * scale
    glow_y = 76.0 * scale
    glow_r = 122.0 * scale
    shadow_cx = 128.0 * scale
    shadow_cy = 206.0 * scale
    shadow_rx = 86.0 * scale
    shadow_ry = 18.0 * scale
    badge_radius = 26.0 * scale
    badge_cx = size - margin - badge_radius * 0.85
    badge_cy = margin + badge_radius * 0.9
    curve_points = [
        (56.0 * scale, 162.0 * scale),
        (84.0 * scale, 154.0 * scale),
        (108.0 * scale, 138.0 * scale),
        (130.0 * scale, 122.0 * scale),
        (152.0 * scale, 108.0 * scale),
        (176.0 * scale, 100.0 * scale),
        (206.0 * scale, 100.0 * scale),
    ]
    pixels = bytearray(size * size * 4)

    for y in range(size):
        for x in range(size):
            px = x + 0.5
            py = y + 0.5
            dist_box = rounded_rect_distance(
                px,
                py,
                center,
                center,
                center - margin,
                center - margin,
                radius,
            )
            fill = clamp01((1.5 - dist_box) / 1.5)
            color = (0, 0, 0, 0)

            if fill > 0.0:
                t = py / max(1.0, size - 1.0)
                base_r, base_g, base_b = lerp_color(style["bg_top"], style["bg_bottom"], t)
                glow = clamp01(1.0 - math.hypot(px - glow_x, py - glow_y) / glow_r)
                base = (
                    clamp255(base_r + glow * style["glow"][0]),
                    clamp255(base_g + glow * style["glow"][1]),
                    clamp255(base_b + glow * style["glow"][2]),
                    clamp255(fill * 255.0),
                )
                color = composite(color, base)

                shadow = clamp01(
                    1.0
                    - (
                        ((px - shadow_cx) / shadow_rx) ** 2
                        + ((py - shadow_cy) / shadow_ry) ** 2
                    )
                )
                if shadow > 0.0:
                    color = composite(color, (0, 0, 0, clamp255(shadow * 38.0)))

                border = band_alpha(dist_box, 0.0, border_width, 1.0)
                if border > 0.0:
                    color = composite(color, (*style["border"], clamp255(border * 170.0)))

                dist_center = math.hypot(px - center, py - center)
                ring = band_alpha(dist_center, ring_radius, ring_half_width, 1.2)
                if ring > 0.0:
                    color = composite(color, (*style["ring"], clamp255(ring * 170.0)))

                angle = (
                    math.degrees(math.atan2(py - center, px - center)) + 360.0
                ) % 360.0
                if 210.0 <= angle <= 330.0:
                    arc = band_alpha(dist_center, ring_radius, ring_half_width, 1.0)
                    if arc > 0.0:
                        color = composite(color, (*style["arc"], clamp255(arc * 220.0)))

                min_curve_distance = 1e9
                for index in range(len(curve_points) - 1):
                    ax, ay = curve_points[index]
                    bx, by = curve_points[index + 1]
                    min_curve_distance = min(
                        min_curve_distance,
                        point_segment_distance(px, py, ax, ay, bx, by),
                    )
                curve = band_alpha(min_curve_distance, 0.0, curve_half_width, 1.0)
                if curve > 0.0:
                    color = composite(color, (*style["curve"], clamp255(curve * 255.0)))

                for node_x, node_y in curve_points:
                    node = band_alpha(
                        math.hypot(px - node_x, py - node_y), 0.0, node_radius, 1.0
                    )
                    if node > 0.0:
                        color = composite(color, (*style["node"], clamp255(node * 245.0)))

                badge_kind = style["badge"]
                if badge_kind == "diamond":
                    dist = abs(px - badge_cx) + abs(py - badge_cy)
                    badge = clamp01((badge_radius * 0.95 - dist) / max(1.0, 1.8 * scale))
                    if badge > 0.0:
                        color = composite(color, (*style["badge_primary"], clamp255(badge * 255.0)))
                        highlight = clamp01((badge_radius * 0.45 - (dist + (py - badge_cy) * 0.6)) / max(1.0, 1.2 * scale))
                        if highlight > 0.0:
                            color = composite(color, (*style["badge_secondary"], clamp255(highlight * 180.0)))
                elif badge_kind == "circle":
                    dist = math.hypot(px - badge_cx, py - badge_cy)
                    badge = band_alpha(dist, 0.0, badge_radius, max(1.0, 1.6 * scale))
                    if badge > 0.0:
                        color = composite(color, (*style["badge_primary"], clamp255(badge * 255.0)))
                        highlight = band_alpha(
                            math.hypot(px - (badge_cx - badge_radius * 0.28), py - (badge_cy - badge_radius * 0.28)),
                            0.0,
                            badge_radius * 0.42,
                            max(1.0, 1.2 * scale),
                        )
                        if highlight > 0.0:
                            color = composite(color, (*style["badge_secondary"], clamp255(highlight * 180.0)))
                elif badge_kind == "split":
                    dist = math.hypot(px - badge_cx, py - badge_cy)
                    badge = band_alpha(dist, 0.0, badge_radius, max(1.0, 1.6 * scale))
                    if badge > 0.0:
                        badge_color = style["badge_primary"] if px <= badge_cx else style["badge_secondary"]
                        color = composite(color, (*badge_color, clamp255(badge * 255.0)))
                        seam = band_alpha(abs(px - badge_cx), 0.0, max(1.0, 1.4 * scale), max(1.0, 1.0 * scale))
                        if seam > 0.0:
                            color = composite(color, (250, 250, 250, clamp255(seam * 120.0)))

            offset = (y * size + x) * 4
            pixels[offset + 0] = color[0]
            pixels[offset + 1] = color[1]
            pixels[offset + 2] = color[2]
            pixels[offset + 3] = color[3]

    return bytes(pixels)


def write_ico(path, variant, sizes):
    images = []
    for size in sizes:
        images.append((size, rgba_to_png(render_icon(size, variant), size)))

    header = struct.pack("<HHH", 0, 1, len(images))
    directory = bytearray()
    image_data = bytearray()
    offset = 6 + 16 * len(images)

    for size, png_bytes in images:
        directory.extend(
            struct.pack(
                "<BBBBHHII",
                0 if size >= 256 else size,
                0 if size >= 256 else size,
                0,
                0,
                1,
                32,
                len(png_bytes),
                offset,
            )
        )
        image_data.extend(png_bytes)
        offset += len(png_bytes)

    with open(path, "wb") as handle:
        handle.write(header)
        handle.write(directory)
        handle.write(image_data)


def _any_newer(sources, target):
    """Return True if any source file is newer than the target, or if target is missing."""
    if not os.path.exists(target):
        return True
    target_mtime = os.path.getmtime(target)
    for src in sources:
        if os.path.exists(src) and os.path.getmtime(src) > target_mtime:
            return True
    return False


def generate_icon():
    """Generate the main app icon and tray-state icon variants if stale."""
    build_script = os.path.join(SCRIPT_DIR, "build.py")
    for variant, path, sizes in ICON_OUTPUTS:
        if _any_newer([build_script], path):
            write_ico(path, variant, sizes)


def generate_resource_script():
    """Generate the deterministic Windows resource script if missing or stale."""
    current = None
    if os.path.exists(ICON_RC):
        with open(ICON_RC, "r", encoding="utf-8", errors="replace") as handle:
            current = handle.read()
    if current != ICON_RC_CONTENT:
        with open(ICON_RC, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(ICON_RC_CONTENT)


def compile_resources():
    """Compile the Windows resource file if stale."""
    generate_resource_script()
    sources = [ICON_RC] + [path for _, path, _ in ICON_OUTPUTS]
    if not _any_newer(sources, ICON_RES):
        return

    if os.path.exists(ICON_RES):
        os.remove(ICON_RES)

    cmd = [
        ZIG_EXE,
        "rc",
        "/x",
        f"/fo{ICON_RES}",
        ICON_RC,
    ]
    print(f"Compiling resources: {os.path.basename(ICON_RC)}")
    result = subprocess.run(cmd, cwd=SCRIPT_DIR)
    if result.returncode != 0 or not os.path.exists(ICON_RES):
        print("Resource compilation FAILED")
        sys.exit(1)


def verify_sha256(path, expected):
    """Verify file SHA-256 matches expected value."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest().lower() == expected.lower()


def safe_extract_target(base_dir, archive_name):
    """Resolve an archive member under base_dir and reject traversal."""
    relative = archive_name.replace("\\", "/")
    parts = relative.split("/", 1)
    if len(parts) != 2 or not parts[1]:
        return None
    relative = os.path.normpath(parts[1])
    if os.path.isabs(relative) or relative == ".." or relative.startswith(".." + os.sep):
        raise RuntimeError(f"Unsafe Zig archive member: {archive_name}")
    base_abs = os.path.abspath(base_dir)
    target = os.path.abspath(os.path.join(base_abs, relative))
    if os.path.commonpath([base_abs, target]) != base_abs:
        raise RuntimeError(f"Unsafe Zig archive member: {archive_name}")
    return target


def prepare_work_subdir(name):
    """Create a clean build scratch subdirectory inside the repository."""
    base_abs = os.path.abspath(BUILD_WORK_DIR)
    target = os.path.abspath(os.path.join(base_abs, name))
    if os.path.commonpath([base_abs, target]) != base_abs:
        raise RuntimeError(f"Unsafe build scratch path: {target}")
    if os.path.exists(target):
        shutil.rmtree(target)
    os.makedirs(target, exist_ok=True)
    return target


def cleanup_work_subdir(path):
    if not path:
        return
    base_abs = os.path.abspath(BUILD_WORK_DIR)
    target = os.path.abspath(path)
    if os.path.commonpath([base_abs, target]) == base_abs and os.path.exists(target):
        shutil.rmtree(target, ignore_errors=True)


def download_zig():
    """Download and extract Zig compiler."""
    if os.path.exists(ZIG_EXE):
        print(f"Zig already present at {ZIG_EXE}")
        return

    print(f"Downloading Zig {ZIG_VERSION}...")
    archive_path = os.path.join(SCRIPT_DIR, f"zig{_ZIG_ARCHIVE_EXT}")

    try:
        urllib.request.urlretrieve(ZIG_URL, archive_path)
    except Exception as exc:
        print(f"Failed to download Zig: {exc}")
        print(f"Please download manually from: {ZIG_URL}")
        print(f"Extract to: {ZIG_DIR}")
        sys.exit(1)

    if ZIG_SHA256 and not verify_sha256(archive_path, ZIG_SHA256):
        os.remove(archive_path)
        print("ERROR: Zig archive SHA-256 verification failed")
        sys.exit(1)

    print("Extracting Zig...")
    os.makedirs(ZIG_DIR, exist_ok=True)

    if _ZIG_ARCHIVE_EXT == ".zip":
        with zipfile.ZipFile(archive_path, "r") as archive:
            for member in archive.namelist():
                target = safe_extract_target(ZIG_DIR, member)
                if not target:
                    continue
                if member.endswith("/"):
                    os.makedirs(target, exist_ok=True)
                else:
                    os.makedirs(os.path.dirname(target), exist_ok=True)
                    with open(target, "wb") as handle:
                        handle.write(archive.read(member))
    else:
        with tarfile.open(archive_path, "r:xz") as archive:
            for member in archive.getmembers():
                target = safe_extract_target(ZIG_DIR, member.name)
                if not target or member.issym() or member.islnk():
                    continue
                if member.isdir():
                    os.makedirs(target, exist_ok=True)
                else:
                    os.makedirs(os.path.dirname(target), exist_ok=True)
                    src = archive.extractfile(member)
                    if src:
                        with src, open(target, "wb") as handle:
                            handle.write(src.read())
                        if member.mode:
                            os.chmod(target, member.mode & 0o777)

    os.remove(archive_path)

    if not os.path.exists(ZIG_EXE):
        print(f"ERROR: {_ZIG_EXE_NAME} not found after extraction")
        sys.exit(1)

    print(f"Zig installed at {ZIG_EXE}")

    # Write integrity sentinel for future builds
    sentinel = ZIG_EXE + ".sha256"
    h = hashlib.sha256()
    with open(ZIG_EXE, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    with open(sentinel, "w", encoding="utf-8") as f:
        f.write(h.hexdigest().lower())


def finalize_output(temp_output, output_path, backup_path=None):
    if not os.path.exists(temp_output):
        print(f"Compilation reported success but {temp_output} is missing")
        sys.exit(1)

    if backup_path and os.path.exists(backup_path):
        os.remove(backup_path)

    replaced_existing = False
    if os.path.exists(output_path):
        try:
            if backup_path:
                os.replace(output_path, backup_path)
            else:
                os.remove(output_path)
            replaced_existing = True
        except OSError as exc:
            print(f"WARNING: Could not replace existing output: {exc}")
            print(f"Built file kept at: {temp_output}")
            sys.exit(1)

    try:
        os.replace(temp_output, output_path)
    except OSError as exc:
        if backup_path and replaced_existing and os.path.exists(backup_path) and not os.path.exists(output_path):
            os.replace(backup_path, output_path)
        print(f"Failed to finalize output: {exc}")
        print(f"Built file kept at: {temp_output}")
        sys.exit(1)

    size = os.path.getsize(output_path)
    print(f"Build successful: {output_path} ({size:,} bytes / {size / 1024:.1f} KB)")


def get_windows_gui_compile_command(temp_output):
    """Return the command array for compiling the Windows GUI executable."""
    return [
        ZIG_EXE,
        "c++",
        *COMMON_FLAGS,
        *WINDOWS_FLAGS,
        "-o",
        temp_output,
        *WINDOWS_SOURCE_FILES,
        ICON_RES,
        *WINDOWS_LINK_LIBS,
    ]


def get_windows_service_compile_command(temp_output):
    """Return the command array for compiling the Windows service executable."""
    return [
        ZIG_EXE,
        "c++",
        *COMMON_FLAGS,
        *WINDOWS_FLAGS,
        "-DGREEN_CURVE_SERVICE_BINARY=1",
        "-o",
        temp_output,
        *WINDOWS_SOURCE_FILES,
        *WINDOWS_SERVICE_LINK_LIBS,
    ]


def get_linux_compile_command(temp_output):
    """Return the command array for compiling the Linux executable."""
    return [
        ZIG_EXE,
        "c++",
        *COMMON_FLAGS,
        *LINUX_FLAGS,
        "-o",
        temp_output,
        *LINUX_SOURCE_FILES,
    ]


def compile_windows_binary(output_path=WINDOWS_OUTPUT_EXE, temp_output=WINDOWS_TEMP_OUTPUT_EXE, backup_path=WINDOWS_BACKUP_EXE, finalize=True):
    """Compile the Windows GUI executable using Zig's bundled clang."""
    missing_sources = [path for path in WINDOWS_SOURCE_FILES if not os.path.exists(path)]
    if missing_sources:
        print("ERROR: Missing source files:")
        for path in missing_sources:
            print(f"  {path}")
        sys.exit(1)

    generate_icon()
    compile_resources()

    if os.path.exists(temp_output):
        os.remove(temp_output)

    cmd = get_windows_gui_compile_command(temp_output)

    print(f"Compiling {len(WINDOWS_SOURCE_FILES)} source files -> {os.path.basename(output_path)}")
    print(f"  Command: {' '.join(cmd)}")

    result = subprocess.run(cmd, cwd=SCRIPT_DIR)
    if result.returncode != 0:
        if os.path.exists(temp_output):
            os.remove(temp_output)
        print("Compilation FAILED")
        sys.exit(1)

    if finalize:
        finalize_output(temp_output, output_path, backup_path)
    else:
        size = os.path.getsize(temp_output)
        print(f"Check build successful: {temp_output} ({size:,} bytes / {size / 1024:.1f} KB)")


def compile_windows_service_binary(output_path=WINDOWS_SERVICE_OUTPUT_EXE, temp_output=WINDOWS_SERVICE_TEMP_OUTPUT_EXE, backup_path=WINDOWS_SERVICE_BACKUP_EXE, finalize=True):
    """Compile the dedicated Windows service executable."""
    missing_sources = [path for path in WINDOWS_SOURCE_FILES if not os.path.exists(path)]
    if missing_sources:
        print("ERROR: Missing source files:")
        for path in missing_sources:
            print(f"  {path}")
        sys.exit(1)

    if os.path.exists(temp_output):
        os.remove(temp_output)

    cmd = get_windows_service_compile_command(temp_output)

    print(f"Compiling {len(WINDOWS_SOURCE_FILES)} source files -> {os.path.basename(output_path)}")
    print(f"  Command: {' '.join(cmd)}")

    result = subprocess.run(cmd, cwd=SCRIPT_DIR)
    if result.returncode != 0:
        if os.path.exists(temp_output):
            os.remove(temp_output)
        print("Compilation FAILED")
        sys.exit(1)

    if finalize:
        finalize_output(temp_output, output_path, backup_path)
    else:
        size = os.path.getsize(temp_output)
        print(f"Check build successful: {temp_output} ({size:,} bytes / {size / 1024:.1f} KB)")


def compile_linux_binary(output_path=LINUX_OUTPUT_BIN, temp_output=LINUX_TEMP_OUTPUT_BIN, backup_path=LINUX_BACKUP_BIN, finalize=True):
    """Cross-compile the Linux terminal build as a static musl binary."""
    missing_sources = [path for path in LINUX_SOURCE_FILES if not os.path.exists(path)]
    if missing_sources:
        print("ERROR: Missing Linux source files:")
        for path in missing_sources:
            print(f"  {path}")
        sys.exit(1)

    if os.path.exists(temp_output):
        os.remove(temp_output)

    cmd = get_linux_compile_command(temp_output)

    print(f"Compiling {len(LINUX_SOURCE_FILES)} source files -> {os.path.basename(output_path)}")
    print(f"  Command: {' '.join(cmd)}")

    result = subprocess.run(cmd, cwd=SCRIPT_DIR)
    if result.returncode != 0:
        if os.path.exists(temp_output):
            os.remove(temp_output)
        print("Compilation FAILED")
        sys.exit(1)

    if finalize:
        finalize_output(temp_output, output_path, backup_path)
    else:
        size = os.path.getsize(temp_output)
        print(f"Check build successful: {temp_output} ({size:,} bytes / {size / 1024:.1f} KB)")


def run_check_builds(target, generate_lsp=True):
    """Build selected targets into a temporary directory without replacing release outputs."""
    if generate_lsp:
        generate_lsp_files()
    tmp = prepare_work_subdir("check")
    try:
        if target in ("windows", "all"):
            compile_windows_binary(
                output_path=os.path.join(tmp, "greencurve.exe"),
                temp_output=os.path.join(tmp, "greencurve.exe.new"),
                backup_path="",
                finalize=False,
            )
            compile_windows_service_binary(
                output_path=os.path.join(tmp, "greencurve-service.exe"),
                temp_output=os.path.join(tmp, "greencurve-service.exe.new"),
                backup_path="",
                finalize=False,
            )
        if target in ("linux", "all"):
            compile_linux_binary(
                output_path=os.path.join(tmp, f"greencurve-{LINUX_TARGET}"),
                temp_output=os.path.join(tmp, f"greencurve-{LINUX_TARGET}.new"),
                backup_path="",
                finalize=False,
            )
    finally:
        cleanup_work_subdir(tmp)


def compile_flags_for_lsp(flags):
    result = []
    skip_next = False
    for index, flag in enumerate(flags):
        if skip_next:
            skip_next = False
            continue
        if flag in ("-o",):
            skip_next = True
            continue
        if flag in ("-static", "-s", "-pie"):
            continue
        if flag.startswith("-Wl,"):
            continue
        result.append(flag)
    return result


def generate_lsp_files():
    """Generate compile_commands.json for clangd from the real Zig build flags."""
    entries = []
    dummy_temp = os.path.join(SCRIPT_DIR, "dummy.out")
    gui_cmd = get_windows_gui_compile_command(dummy_temp)
    service_cmd = get_windows_service_compile_command(dummy_temp)
    linux_cmd = get_linux_compile_command(dummy_temp)
    windows_flags = compile_flags_for_lsp(gui_cmd[2:-len(WINDOWS_SOURCE_FILES) - len(WINDOWS_LINK_LIBS) - 2])
    service_flags = compile_flags_for_lsp(service_cmd[2:-len(WINDOWS_SOURCE_FILES) - len(WINDOWS_SERVICE_LINK_LIBS) - 2])
    linux_flags = compile_flags_for_lsp(linux_cmd[2:-len(LINUX_SOURCE_FILES) - 2])

    entries.append({
        "directory": SCRIPT_DIR,
        "file": os.path.join(SOURCE_DIR, "main.cpp"),
        "arguments": ["clang++", *windows_flags, "-fsyntax-only", os.path.join(SOURCE_DIR, "main.cpp")],
    })
    entries.append({
        "directory": SCRIPT_DIR,
        "file": os.path.join(SOURCE_DIR, "main.cpp"),
        "arguments": ["clang++", *service_flags, "-fsyntax-only", os.path.join(SOURCE_DIR, "main.cpp")],
    })
    for source in LINUX_SOURCE_FILES:
        entries.append({
            "directory": SCRIPT_DIR,
            "file": source,
            "arguments": ["clang++", *linux_flags, "-fsyntax-only", source],
        })
    for source in (os.path.join(SOURCE_DIR, "app_shared.cpp"), os.path.join(SOURCE_DIR, "config_utils.cpp"), os.path.join(SOURCE_DIR, "fan_curve.cpp")):
        entries.append({
            "directory": SCRIPT_DIR,
            "file": source,
            "arguments": ["clang++", *windows_flags, "-fsyntax-only", source],
        })

    path = os.path.join(SCRIPT_DIR, "compile_commands.json")
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(entries, handle, indent=2)
        handle.write("\n")
    print(f"Generated {path}")


def run_regression_tests(extra_flags=None):
    """Run pure regression tests that do not touch GPU hardware."""
    harness = r'''
#include "fan_curve.h"

void invalidate_tray_profile_cache() {}

int main(int argc, char** argv) {
    InitializeCriticalSection(&g_configLock);

    if (APP_DEBUG_DEFAULT_ENABLED != 1) return 20;

    int point = -1;
    if (!parse_cli_point_arg_w(L"--point0", &point) || point != 0) return 21;
    if (!parse_cli_point_arg_w(L"--point127", &point) || point != 127) return 22;
    if (parse_cli_point_arg_w(L"--point128", &point)) return 23;
    if (parse_cli_point_arg_w(L"--pointabc", &point)) return 24;
    if (parse_cli_point_arg_w(L"--point-1", &point)) return 25;

    if (!gpu_family_uses_best_guess_backend(GPU_FAMILY_PASCAL)) return 26;
    if (!gpu_family_uses_best_guess_backend(GPU_FAMILY_TURING)) return 27;
    if (!gpu_family_uses_best_guess_backend(GPU_FAMILY_AMPERE)) return 28;
    if (gpu_family_uses_best_guess_backend(GPU_FAMILY_LOVELACE)) return 29;
    if (gpu_family_uses_best_guess_backend(GPU_FAMILY_BLACKWELL)) return 30;

    FanCurveConfig cfg = {};
    fan_curve_set_default(&cfg);
    fan_curve_normalize(&cfg);
    char err[128] = {};
    if (!fan_curve_validate(&cfg, err, sizeof(err))) return 1;
    if (fan_curve_active_count(&cfg) != 5) return 2;
    if (fan_curve_interpolate_percent(&cfg, 30) != 20) return 3;
    int mid = fan_curve_interpolate_percent(&cfg, 52);
    if (mid < 42 || mid > 48) return 4;
    cfg.points[1].fanPercent = 10;
    if (fan_curve_validate(&cfg, err, sizeof(err))) return 5;
    cfg.points[1].fanPercent = 35;
    cfg.pollIntervalMs = 333;
    fan_curve_normalize(&cfg);
    if (cfg.pollIntervalMs != 250) return 6;

    if (argc < 2 || !argv[1] || !argv[1][0]) return 31;
    DeleteFileA(argv[1]);
    HANDLE configMutex = nullptr;
    if (!enter_config_storage_lock(&configMutex)) return 32;
    leave_config_storage_lock(configMutex);
    if (get_config_int(argv[1], "debug", "enabled", 77) != 77) return 33;
    if (!set_config_int(argv[1], "debug", "enabled", APP_DEBUG_DEFAULT_ENABLED)) return 34;
    if (!config_section_has_keys(argv[1], "debug")) return 35;
    if (get_config_int(argv[1], "debug", "enabled", 0) != 1) return 36;
    if (!set_config_int(argv[1], "runtime", "selective_gpu_offset_mhz", 45)) return 37;
    if (get_config_int(argv[1], "runtime", "selective_gpu_offset_mhz", 0) != 45) return 38;
    DeleteFileA(argv[1]);

    // F-15-002: degenerate/empty fan curve interpolation returns 100 (safe fallback)
    {
        FanCurveConfig empty = {};
        if (fan_curve_interpolate_percent(&empty, 50) != 100) return 40;
    }

    // fan_curve_clamp_percentages
    {
        FanCurveConfig clampCfg = {};
        fan_curve_set_default(&clampCfg);
        fan_curve_clamp_percentages(&clampCfg, 40, 80);
        for (int i = 0; i < FAN_CURVE_MAX_POINTS; i++) {
            if (clampCfg.points[i].enabled) {
                if (clampCfg.points[i].fanPercent < 40 || clampCfg.points[i].fanPercent > 80) return 41;
            }
        }
    }

    // fan_curve_equals
    {
        FanCurveConfig a = {}, b = {};
        fan_curve_set_default(&a);
        fan_curve_set_default(&b);
        if (!fan_curve_equals(&a, &b)) return 42;
        a.pollIntervalMs = 999;
        if (fan_curve_equals(&a, &b)) return 43;
    }

    // fan_curve_has_high_temp_low_fan_warning
    {
        FanCurveConfig safe = {};
        fan_curve_set_default(&safe);
        if (fan_curve_has_high_temp_low_fan_warning(&safe)) return 44;
        FanCurveConfig danger = {};
        danger.points[0] = { true, 85, 20 };
        danger.points[1] = { true, 95, 30 };
        if (!fan_curve_has_high_temp_low_fan_warning(&danger)) return 45;
    }

    // validate_desired_settings_for_ipc clamps out-of-range values
    {
        DesiredSettings ds = {};
        ds.hasPowerLimit = true;
        ds.powerLimitPct = 10;
        ds.hasGpuOffset = true;
        ds.gpuOffsetMHz = 5000;
        ds.hasMemOffset = true;
        ds.memOffsetMHz = -9000;
        ds.hasFan = true;
        ds.fanPercent = 200;
        for (int ci = 0; ci < VF_NUM_POINTS; ci++) {
            ds.hasCurvePoint[ci] = true;
            ds.curvePointMHz[ci] = 9999u;
        }
        validate_desired_settings_for_ipc(&ds);
        if (ds.powerLimitPct != 50) return 50;
        if (ds.gpuOffsetMHz != 1000) return 51;
        if (ds.memOffsetMHz != -5000) return 52;
        if (ds.fanPercent != 100) return 53;
        if (ds.curvePointMHz[0] != 5000u) return 54;
    }

    DeleteCriticalSection(&g_configLock);
    return 0;
}
'''
    tmp = prepare_work_subdir("test")
    try:
        harness_path = os.path.join(tmp, "fan_curve_regression.cpp")
        test_exe = os.path.join(tmp, "fan_curve_regression.exe" if sys.platform == "win32" else "fan_curve_regression")
        with open(harness_path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(harness)
        cmd = [
            ZIG_EXE,
            "c++",
            "-std=c++17",
            "-DNDEBUG",
            "-fno-exceptions",
            "-fno-rtti",
            f"-I{SOURCE_DIR}",
            "-o",
            test_exe,
            harness_path,
            os.path.join(SOURCE_DIR, "fan_curve.cpp"),
            os.path.join(SOURCE_DIR, "config_utils.cpp"),
            os.path.join(SOURCE_DIR, "app_shared.cpp"),
        ]
        if extra_flags:
            cmd.extend(extra_flags)
        if sys.platform == "win32":
            cmd.extend(["-luser32", "-lgdi32"])
        print("Compiling pure regression tests")
        result = subprocess.run(cmd, cwd=SCRIPT_DIR)
        if result.returncode != 0:
            print("Regression test compilation FAILED")
            sys.exit(result.returncode)
        config_path = os.path.join(tmp, "config_roundtrip.ini")
        print("Running pure regression tests")
        result = subprocess.run([test_exe, config_path], cwd=SCRIPT_DIR)
        if result.returncode != 0:
            print(f"Regression tests FAILED ({result.returncode})")
            sys.exit(result.returncode)
        run_source_regression_checks()
        print("Regression tests passed")
    finally:
        cleanup_work_subdir(tmp)


def require_text(path, needle, label):
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        text = handle.read()
    if needle not in text:
        print(f"Regression source check FAILED: {label}")
        sys.exit(1)


def run_source_regression_checks():
    main_cpp = os.path.join(SOURCE_DIR, "main.cpp")
    entry_cpp = os.path.join(SOURCE_DIR, "entry.cpp")
    diagnostics_cpp = os.path.join(SOURCE_DIR, "main_diagnostics.cpp")
    service_ipc_cpp = os.path.join(SOURCE_DIR, "main_service_ipc.cpp")
    service_server_cpp = os.path.join(SOURCE_DIR, "main_service_server.cpp")
    config_profiles_ui_cpp = os.path.join(SOURCE_DIR, "config_profiles_ui.cpp")
    gpu_backend_apply_cpp = os.path.join(SOURCE_DIR, "gpu_backend_apply.cpp")
    main_gpu_state_cpp = os.path.join(SOURCE_DIR, "main_gpu_state.cpp")
    main_shell_cpp = os.path.join(SOURCE_DIR, "main_shell.cpp")
    main_fan_runtime_cpp = os.path.join(SOURCE_DIR, "main_fan_runtime.cpp")
    runtime_nvml_cpp = os.path.join(SOURCE_DIR, "main_runtime_nvml.cpp")
    shared_h = os.path.join(SOURCE_DIR, "app_shared.h")
    build_script = os.path.join(SCRIPT_DIR, "build.py")
    gitignore = os.path.join(SCRIPT_DIR, ".gitignore")

    require_text(shared_h, "APP_DEBUG_DEFAULT_ENABLED 1", "debug logging remains default-on")
    require_text(shared_h, "APP_EDITION", "window title edition text exists")
    require_text(shared_h, "APP_TITLE           APP_NAME \" v\" APP_VERSION", "plain title macro exists")
    require_text(shared_h, "SERVICE_PROTOCOL_VERSION = 6", "service protocol version bumped")
    require_text(shared_h, "resetOcBeforeApply", "GUI apply reset-before-apply protocol flag exists")
    require_text(shared_h, "GpuAdapterInfo", "GPU adapter identity protocol exists")
    require_text(shared_h, "APP_BUILD_NUMBER", "build number define exists")
    require_text(shared_h, "serviceBuildNumber", "service response carries build number")
    require_text(shared_h, "serviceVersion[32]", "service response carries version")
    require_text(diagnostics_cpp, "protocol=%lu", "session marker logs IPC protocol")
    require_text(diagnostics_cpp, "build=%lu", "session marker logs build number")
    require_text(diagnostics_cpp, "close_debug_log_file", "debug log file cleanup exists")
    require_text(diagnostics_cpp, "open_debug_log_file_locked", "debug log file open helper exists")
    require_text(diagnostics_cpp, "green_curve_unhandled_exception_filter", "crash filter exists")
    require_text(main_cpp, "SERVICE_PIPE_SERVER_IO_TIMEOUT_MS", "service pipe server I/O timeout exists")
    require_text(service_server_cpp, "CancelIoEx(pipe, &ov)", "stalled pipe operations are cancellable")
    require_text(service_server_cpp, "response.serviceBuildNumber", "service responses include build number")
    require_text(service_server_cpp, "stop_service_for_binary_update", "service repair stops old service before replacing binary")
    require_text(service_server_cpp, "SERVICE_CHANGE_CONFIG | SERVICE_START | SERVICE_STOP | SERVICE_QUERY_STATUS", "service repair can stop installed service")
    require_text(service_ipc_cpp, "service_client_ping: identity mismatch", "GUI rejects mismatched service version identity")
    require_text(service_ipc_cpp, "compatible build mismatch accepted", "GUI accepts compatible service build-number drift")
    require_text(service_ipc_cpp, "backgroundServiceError", "service ping failures are surfaced to the GUI")
    require_text(service_ipc_cpp, "GetNamedPipeServerProcessId", "GUI verifies service pipe server PID")
    require_text(service_ipc_cpp, "ensure_secure_service_binary_path", "service install uses secure Program Files copy")
    require_text(service_ipc_cpp, "CopyFileW(sourcePath, tempPath", "service binary is staged before install")
    require_text(service_ipc_cpp, "wait_for_helper_process_bounded", "elevated helper waits are bounded")
    require_text(config_profiles_ui_cpp, "maybe_load_selected_profile_to_gui_without_apply", "startup restores selected profile into GUI without applying")
    require_text(config_profiles_ui_cpp, "repair needed", "broken installed service advertises repair state")
    require_text(os.path.join(SOURCE_DIR, "ui_main_window.cpp"), "Repair and restart the background service", "broken installed service click repairs instead of removing")
    require_text(config_profiles_ui_cpp, "GPU settings were not applied", "startup selected profile restore is GUI-only")
    require_text(gpu_backend_apply_cpp, "attempting driver write anyway", "memory offsets outside reported range are attempted")
    require_text(main_gpu_state_cpp, "live_selective_gpu_offset_matches_requested_shape", "persisted selective GPU offset is verified against live VF shape")
    require_text(main_gpu_state_cpp, "runtime selective: ignoring persisted request", "stale persisted selective GPU offset is ignored")
    require_text(main_gpu_state_cpp, "non-selective request clears runtime state", "uniform GPU offsets clear runtime selective state")
    require_text(gpu_backend_apply_cpp, "interactive && !g_app.isServiceProcess", "service apply does not inherit stale GUI lock state")
    require_text(gpu_backend_apply_cpp, "post-apply lock clear: no lock requested", "service no-lock applies clear stale lock markers")
    require_text(gpu_backend_apply_cpp, "reset_oc_before_gui_apply", "GUI OC applies reset stale OC baseline before applying")
    require_text(gpu_backend_apply_cpp, "Restoring the existing VF curve after the memory offset did not verify", "VF preservation failures are reported")
    require_text(runtime_nvml_cpp, "rollback_changed_fans", "manual multi-fan writes roll back partial failures")
    require_text(runtime_nvml_cpp, "nvml_select_device_for_selected_gpu", "NVML device is matched to selected GPU")
    require_text(diagnostics_cpp, "write_text_file_atomic_service", "service file writes use hardened writer")
    require_text(os.path.join(SOURCE_DIR, "ui_main.cpp"), "gpuSelectY = dp(10)", "GPU selector lives in the graph header gap")
    require_text(main_gpu_state_cpp, "Writes are intentionally enabled", "best-guess VF writes remain explicitly enabled")
    require_text(main_shell_cpp, "preserving requested value", "config memory offsets are not clamped to reported range")
    require_text(runtime_nvml_cpp, "parse_cli_point_arg_w(arg, &idx)", "CLI point parsing is strict")
    require_text(entry_cpp, "set_main_window_title", "window caption helper exists")
    require_text(entry_cpp, "APP_EDITION", "window title edition macro remains present")
    require_text(entry_cpp, "SetWindowTextA", "window caption uses ANSI text write")
    require_text(entry_cpp, "RegisterClassExA", "main window uses ANSI class registration")
    require_text(entry_cpp, "CreateWindowExA", "main window uses ANSI creation path")
    require_text(main_fan_runtime_cpp, "FindWindowA", "single-instance lookup uses ANSI class matching")
    require_text(build_script, "--check", "build check flag exists")
    require_text(build_script, "--test", "test flag exists")
    require_text(build_script, "compile_commands.json", "LSP database generation exists")
    require_text(gitignore, "*.7z", "release archives are ignored")
    # NOTE: Zig 0.13.0 does not emit stack canaries on Windows despite
    # -fstack-protector-strong. This is a known toolchain limitation.
    # The flag is kept so future Zig versions will automatically enable it.
    require_text(build_script, "-fstack-protector-strong", "stack protector flag retained for future toolchain support")
    require_text(build_script, "-fPIE", "Linux PIE hardening retained")
    require_text(build_script, "-Wl,-z,relro,-z,now", "Linux RELRO/BIND_NOW hardening retained")
    require_text(build_script, "-Wl,-z,noexecstack", "Linux non-executable stack hardening retained")


def parse_args():
    parser = argparse.ArgumentParser(description="Build Green Curve targets with Zig")
    parser.add_argument(
        "--target",
        choices=("windows", "linux", "all"),
        default="windows",
        help="Which target to build (default: windows)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Build selected targets into a temporary directory and generate LSP metadata",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run pure regression tests that do not touch GPU hardware",
    )
    parser.add_argument(
        "--lsp",
        action="store_true",
        help="Generate compile_commands.json for clangd and exit",
    )
    parser.add_argument(
        "--sanitizer",
        action="store_true",
        help="Build with UndefinedBehaviorSanitizer",
    )
    return parser.parse_args()


def generate_version_nsh():
    _VERSION_NSH_PATH = os.path.join(SCRIPT_DIR, "version.nsh")
    with open(_VERSION_NSH_PATH, "w", encoding="utf-8") as _vnf:
        _vnf.write(f'!define VERSION "{APP_VERSION}"\n')


def verify_cached_zig():
    if not os.path.exists(ZIG_EXE):
        return
    sentinel = ZIG_EXE + ".sha256"
    current = hashlib.sha256()
    with open(ZIG_EXE, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            current.update(chunk)
    digest = current.hexdigest().lower()
    if os.path.exists(sentinel):
        with open(sentinel, "r", encoding="utf-8") as f:
            expected = f.read().strip().lower()
        if digest != expected:
            print(f"ERROR: Cached Zig binary integrity check failed")
            print(f"  Expected: {expected}")
            print(f"  Actual:   {digest}")
            print(f"  Delete the zig/ directory to force a fresh download.")
            sys.exit(1)
    else:
        print("ERROR: Cached Zig binary is missing its integrity sentinel")
        print("  Delete the zig/ directory to force a fresh verified download.")
        sys.exit(1)


def main():
    args = parse_args()
    print("=== Green Curve build ===")
    download_zig()
    verify_cached_zig()
    real_build = not args.lsp and not args.check and not args.test
    configure_build_number(real_build)
    generate_version_nsh()

    # H-001 fix: avoid permanently mutating the global COMMON_FLAGS list.
    # Save the original flags so sanitizer additions do not leak into
    # subsequent release builds in the same process.
    _original_common_flags = COMMON_FLAGS.copy()
    if args.sanitizer:
        COMMON_FLAGS.extend(SANITIZER_FLAGS)
    try:
        if args.lsp:
            generate_lsp_files()
            print("=== Done ===")
            return
        if args.test:
            run_regression_tests(extra_flags=SANITIZER_FLAGS if args.sanitizer else None)
            if not args.check:
                print("=== Done ===")
                return
        if args.check:
            run_check_builds(args.target, generate_lsp=not args.sanitizer)
            print("=== Done ===")
            return
        generate_lsp_files()
        if args.target in ("windows", "all"):
            compile_windows_binary()
            compile_windows_service_binary()
        if args.target in ("linux", "all"):
            compile_linux_binary()
        print("=== Done ===")
    finally:
        COMMON_FLAGS[:] = _original_common_flags


if __name__ == "__main__":
    main()
