"""Build-state and size-ratchet helpers split out of build.py.

build.py remains the only entry point; this module is one of the one-way
tools dependencies (it never imports build.py).  The helpers moved here are
pure and have no toolchain dependency, so ``python build.py --test`` covers
them on every host.
"""

import hashlib
import os
import sys

# build.py is by far the largest file in the project and was exempt from the
# rule it enforces on everything else.  It is ratcheted here so it can only
# shrink; the target is to get it under the ~800-line guideline by moving the
# test harness and source guards into real files.
# 8994 before the harness moved to tests/regression_main.cpp; lower this as the
# remaining source guards move into a build_checks/ package.
# 5648 before the deterministic icon renderer moved to tools/icon_render.py.
BUILD_SCRIPT_SIZE_RATCHET = 5304

SOURCE_SIZE_RATCHET = {
    "config_profiles.cpp": 883,
    "entry.cpp": 863,
    "gpu_backend.cpp": 972,
    "gpu_backend_apply.cpp": 1320,  # 1333 before gpu_backend_reset_baseline.cpp
    "gpu_core.h": 820,
    "gui_service_state.cpp": 813,
    "main.cpp": 801,
    "main_fan_runtime.cpp": 913,  # 929 before the tray menu moved to gui_tray_menu.cpp
    "main_gpu_front.cpp": 845,
    "main_gpu_state.cpp": 916,
    "main_runtime_nvml.cpp": 901,
    "main_service_persist.cpp": 908,
    "main_service_pipe.cpp": 796,  # 828 before the file-write commands moved out
    "main_state_sync.cpp": 859,
    "ui_main_window.cpp": 1279,
}


def read_int_file(path, default=0):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read().strip()
        return int(text) if text else default
    except (OSError, ValueError):
        return default


def write_text_if_changed(path, text):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            if handle.read() == text:
                return
    except OSError:
        pass
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def iter_build_fingerprint_inputs(script_dir, source_dir):
    for name in ("build.py", "VERSION"):
        path = os.path.join(script_dir, name)
        if os.path.exists(path):
            yield path
    for root, _dirs, files in os.walk(source_dir):
        for name in sorted(files):
            if name.endswith((".cpp", ".h")):
                yield os.path.join(root, name)


def compute_build_fingerprint(script_dir, source_dir):
    digest = hashlib.sha256()
    for path in sorted(iter_build_fingerprint_inputs(script_dir, source_dir)):
        rel = os.path.relpath(path, script_dir).replace("\\", "/")
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        with open(path, "rb") as handle:
            for chunk in iter(lambda: handle.read(65536), b""):
                digest.update(chunk)
        digest.update(b"\0")
    return digest.hexdigest()


def any_newer(sources, target):
    """Return True if any source file is newer than the target, or if target is missing."""
    if not os.path.exists(target):
        return True
    target_mtime = os.path.getmtime(target)
    for src in sources:
        if os.path.exists(src) and os.path.getmtime(src) > target_mtime:
            return True
    return False


def parse_version_parts(version, build_number):
    """Return (major, minor, patch, build) from a version string and build number."""
    parts = version.split(".")
    major = int(parts[0]) if len(parts) > 0 else 0
    minor = int(parts[1]) if len(parts) > 1 else 0
    patch = int(parts[2]) if len(parts) > 2 else 0
    return major, minor, patch, build_number


# Windows .rc VERSIONINFO and manifest templates.  They moved here with the
# version builders; build.py still owns the generated file paths.
ICON_RC_CONTENT = """// Generated by build.py. Do not edit by hand.
101 ICON "greencurve.ico"
111 ICON "greencurve_tray_default.ico"
112 ICON "greencurve_tray_oc.ico"
113 ICON "greencurve_tray_fan.ico"
114 ICON "greencurve_tray_oc_fan.ico"
115 ICON "greencurve_tray_pending.ico"

1 VERSIONINFO
FILEVERSION     VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD
PRODUCTVERSION  VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD
FILEFLAGSMASK   0x3fL
#ifdef _DEBUG
FILEFLAGS       0x1L
#else
FILEFLAGS       0x0L
#endif
FILEOS          0x40004L
FILETYPE        0x1L
FILESUBTYPE     0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "FileDescription", "NVIDIA GPU VF Curve Editor"
            VALUE "FileVersion", "VER_STR"
            VALUE "InternalName", "GreenCurve"
            VALUE "LegalCopyright", "Copyright (c) 2026 aufkrawall. MIT License."
            VALUE "OriginalFilename", "greencurve.exe"
            VALUE "ProductName", "Green Curve"
            VALUE "ProductVersion", "VER_STR"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END

1 24 "greencurve.exe.manifest"
"""

APP_MANIFEST_CONTENT = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity
    type="win32"
    name="GreenCurve"
    version="VER_STR"
    processorArchitecture="amd64"/>
  <description>NVIDIA GPU VF Curve Editor</description>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:windowsSettings
      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
    <asmv3:windowsSettings
      xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
      <dpiAwareness>PerMonitorV2,PerMonitor</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    </application>
  </compatibility>
</assembly>
"""


def build_rc_content(version, build_number):
    """Build RC content with version numbers substituted."""
    major, minor, patch, build = parse_version_parts(version, build_number)
    ver_str = f"{major}.{minor}.{patch}.{build}"
    content = ICON_RC_CONTENT
    content = content.replace("VER_MAJOR", str(major))
    content = content.replace("VER_MINOR", str(minor))
    content = content.replace("VER_PATCH", str(patch))
    content = content.replace("VER_BUILD", str(build))
    content = content.replace("VER_STR", ver_str)
    return content


def build_manifest_content(version, build_number):
    """Build manifest content with version substituted."""
    major, minor, patch, build = parse_version_parts(version, build_number)
    ver_str = f"{major}.{minor}.{patch}.{build}"
    return APP_MANIFEST_CONTENT.replace("VER_STR", ver_str)


def concatenated_gate_surface(work_dir, source_dir, out_name, source_names):
    """Join shards that were split ONLY for the size ratchet into one file the
    source guards can be pointed at.

    A mechanical split moves symbols between files without changing what the
    program does, so every guard naming one of those symbols would otherwise
    have to be hunted down and re-pointed -- and a guard that is silently
    looking at the wrong file still passes for the wrong reason.  Joining the
    shards back into one surface keeps the guards addressed to the logical
    unit they were written about.

    Lives here rather than in build.py because build.py is at its own ratchet,
    which exists to push exactly this kind of helper out of it.
    """
    os.makedirs(work_dir, exist_ok=True)
    path = os.path.join(work_dir, out_name)
    with open(path, "w", encoding="utf-8", errors="ignore") as out:
        for name in source_names:
            with open(os.path.join(source_dir, name), "r",
                      encoding="utf-8", errors="ignore") as shard:
                out.write(shard.read())
                out.write("\n")
    return path


def enforce_build_script_size_ratchet(script_dir):
    path = os.path.join(script_dir, "build.py")
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            lines = sum(1 for _ in handle)
    except OSError:
        return
    if lines > BUILD_SCRIPT_SIZE_RATCHET:
        print("Regression source check FAILED: build.py size ratchet")
        print(f"  build.py: {lines} lines exceeds ratchet "
              f"{BUILD_SCRIPT_SIZE_RATCHET}")
        print("  Move test harness / source guards out rather than raising it.")
        sys.exit(1)


def enforce_source_size_ratchet(script_dir, source_dir, soft_limit=800):
    """Reject new oversized modules and growth in grandfathered modules."""
    enforce_build_script_size_ratchet(script_dir)
    exempt = {"app_shared.h"}
    oversized = []
    violations = []
    for name in sorted(os.listdir(source_dir)):
        if not (name.endswith(".cpp") or name.endswith(".h")):
            continue
        if name in exempt:
            continue
        path = os.path.join(source_dir, name)
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                lines = sum(1 for _ in handle)
        except OSError:
            continue
        if lines > soft_limit:
            oversized.append((lines, name))
            ceiling = SOURCE_SIZE_RATCHET.get(name)
            if ceiling is None:
                violations.append(f"new oversized source/{name}: {lines} lines")
            elif lines > ceiling:
                violations.append(f"source/{name}: {lines} lines exceeds ratchet {ceiling}")
    if oversized:
        oversized.sort(reverse=True)
        print(f"NOTE: {len(oversized)} source file(s) exceed the ~{soft_limit}-line guideline (F-MAINT-1):")
        for lines, name in oversized:
            print(f"  {lines:5d}  source/{name}")
    if violations:
        print("Regression source check FAILED: source-size ratchet")
        for violation in violations:
            print(f"  {violation}")
        sys.exit(1)
