#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 aufkrawall
# SPDX-License-Identifier: MIT
"""Host-correct clang-tidy ratchet for Green Curve.

Kept outside build.py so the main build orchestrator stays under its size
ratchet. The dependency is one-way: this module receives the live build module
as ``ctx`` and never imports it.
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile


# Checks worth failing a build over: real defect classes, not style. Broaden
# only after the existing baseline is cleared enough to keep the gate credible.
TIDY_CHECKS = ",".join([
    "-*",
    "bugprone-*",
    "cert-*",
    "clang-analyzer-*",
    "misc-*",
    "-bugprone-easily-swappable-parameters",
    "-bugprone-narrowing-conversions",
    "-misc-no-recursion",
    "-misc-non-private-member-variables-in-classes",
    "-misc-use-anonymous-namespace",
    "-misc-const-correctness",
    # The project deliberately uses amalgamated .cpp shards.
    "-misc-include-cleaner",
    "-bugprone-suspicious-include",
    "-misc-use-internal-linkage",
    "-clang-analyzer-optin.performance.Padding",
    "-bugprone-reserved-identifier",
    "-cert-dcl37-c",
    "-cert-dcl51-cpp",
    "-cert-dcl50-cpp",
    "-cert-err33-c",
])


def add_arguments(parser):
    parser.add_argument(
        "--tidy", action="store_true",
        help="Run clang-tidy and fail on findings outside the tracked baseline")
    parser.add_argument(
        "--tidy-baseline", action="store_true",
        help="Merge the current findings into the clang-tidy baseline; only "
             "entries whose source file is gone are dropped")


_DIAGNOSTIC_RE = re.compile(
    r"^(.*?):(\d+):(\d+):\s+(warning|error):\s+.*\[([^\]]+)\]\s*$")

# The project deliberately #includes amalgamated .cpp shards into a handful of
# translation units, so most diagnostics land in a file that is not the main
# file.  Whether clang-tidy prints those depends on its version -- LLVM 18
# suppresses them unless a header filter matches, LLVM 20+ shows them -- which
# silently changes the analyzed surface between a developer host and CI.  Pin
# the surface here: shards are always in scope, .h headers stay out.
SHARD_HEADER_FILTER = r"[/\\](source|tests)[/\\][^/\\]*\.cpp$"

_GENERATOR_PREFIX = "# Generated by: "


def _alias_set(checks):
    """Split a diagnostic's bracketed check list into its alias names."""
    return frozenset(name.strip() for name in checks.split(",") if name.strip())


def _entry_key(path, names):
    """Serialize one baseline entry: path, TAB, the check's alias names."""
    return f"{path}\t{','.join(sorted(names))}"


def _parse_diagnostic(line, script_dir):
    """Reduce a diagnostic to (path, alias names), excluding line-number churn."""
    match = _DIAGNOSTIC_RE.match(line.strip())
    if not match:
        return None
    path = os.path.relpath(match.group(1), script_dir).replace("\\", "/")
    return path, _alias_set(match.group(5))


def _parse_entry(entry):
    """Inverse of _entry_key; a legacy entry without a TAB has no check."""
    path, _, checks = entry.partition("\t")
    return path, _alias_set(checks)


def _alias_index(entries):
    """Group (path, alias names) pairs into path -> list of alias sets."""
    index = {}
    for path, names in entries:
        index.setdefault(path, []).append(names)
    return index


def _covered(index, path, names):
    """True when the same check is already recorded for this path.

    clang-tidy prints every *enabled* alias of a check, and which aliases exist
    is a clang-tidy version detail: LLVM 20 promoted cert-env33-c to
    bugprone-command-processor and cert-err34-c to
    bugprone-unchecked-string-to-number-conversion.  One unchanged finding
    therefore prints as "[cert-err34-c]" on Ubuntu's clang-tidy 18 and as
    "[bugprone-unchecked-string-to-number-conversion,cert-err34-c]" on a newer
    host.  Comparing the printed list verbatim made a baseline non-portable and
    failed CI on findings it already carried, so match on set intersection
    instead: one shared name means one check.
    """
    return any(names & recorded for recorded in index.get(path, ()))


def _load_baseline(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r", encoding="utf-8") as handle:
        return {
            line.strip() for line in handle
            if line.strip() and not line.startswith("#")
        }


def _baseline_generator(path):
    """The clang-tidy that wrote the baseline, for version-skew diagnostics."""
    if not os.path.exists(path):
        return "unknown"
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            if line.startswith(_GENERATOR_PREFIX):
                return line[len(_GENERATOR_PREFIX):].strip()
            if not line.startswith("#"):
                break
    return "unrecorded (predates version stamping)"


def _tidy_version(tidy):
    """Short clang-tidy version string; logged so CI skew is self-evident."""
    try:
        result = subprocess.run([tidy, "--version"], text=True,
                                capture_output=True)
    except OSError as exc:
        return f"unknown ({exc})"
    for line in (result.stdout or "").splitlines():
        if "version" in line.lower():
            return line.strip()
    return "unknown"


def _host_tidy(ctx):
    if sys.platform == "win32":
        tidy = os.path.join(
            os.path.dirname(ctx.LLVM_MINGW_CLANG), "clang-tidy.exe")
        if not os.path.exists(tidy):
            tidy = os.path.join(
                os.path.dirname(ctx.LLVM_MINGW_CLANG), "clang-tidy")
        return tidy
    return shutil.which("clang-tidy")


def _host_entries(ctx, entries):
    if sys.platform == "win32":
        return entries
    linux_sources = set(ctx.LINUX_SOURCE_FILES)
    linux_sources.add(
        os.path.join(ctx.SCRIPT_DIR, "tests", "regression_main.cpp"))
    return [
        entry for entry in entries
        if os.path.normpath(entry["file"]) in linux_sources
        and "-mguard=cf" not in entry.get("arguments", [])
    ]


def _windows_extra_args(ctx):
    if sys.platform != "win32":
        return []
    libcxx_include = os.path.join(
        os.path.dirname(os.path.dirname(ctx.LLVM_MINGW_CLANG)),
        "include", "c++", "v1")
    if not os.path.isdir(libcxx_include):
        raise RuntimeError(f"libc++ headers not found at {libcxx_include}")
    return ["--extra-arg=-isystem", f"--extra-arg={libcxx_include}"]


def _merge_baseline(baseline, current, script_dir):
    """Regenerated baseline: everything recorded, plus what this run reported.

    Returns (merged, dropped).  The only entries that leave are the ones whose
    source file is gone, which is the one reason no host will ever report them
    again.  Anything else stays even when unreported, because "unreported here"
    is not "fixed": see the write path in run_clang_tidy().
    """
    gone = {
        entry for entry in baseline
        if not os.path.exists(os.path.join(script_dir, _parse_entry(entry)[0]))
    }
    return (baseline - gone) | current, gone


def _write_baseline(path, keys, version="unknown"):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("# clang-tidy baseline: path<TAB>check[,check-alias...].\n")
        handle.write("# Entries match a diagnostic when any one alias name is\n"
                     "# shared, so the file stays portable across clang-tidy\n"
                     "# versions that rename or alias a check.\n")
        handle.write("# Regenerate with: python build.py --tidy-baseline\n")
        handle.write(f"{_GENERATOR_PREFIX}{version}\n")
        for key in sorted(keys):
            handle.write(key + "\n")


def check_ratchet_wiring(ctx, require_text):
    """Source guards for the ratchet itself (audit F-GATES).

    Lives here rather than in build.py for the same reason as every other gate
    group: the build script has a size ratchet, and a guard belongs next to the
    code it protects.
    """
    path = os.path.join(ctx.SCRIPT_DIR, "tools", "static_analysis.py")
    gates = os.path.join(ctx.SCRIPT_DIR, "tools", "security_gates.py")
    require_text(path, "clang-analyzer-*",
                 "clang-tidy runs the static analyzer families, not just style checks")
    require_text(path, "return 1 if new_findings or execution_failures",
                 "clang-tidy fails the build on findings outside the baseline")
    require_text(path, 'shutil.which("clang-tidy")',
                 "Linux static analysis selects a host-native clang-tidy")
    require_text(path, "include\", \"c++\", \"v1",
                 "clang-tidy is given llvm-mingw's libc++ headers; without them "
                 "every TU reports clang-diagnostic-error")
    # A baseline is written on one host and enforced on another, so neither the
    # printed alias names nor the analyzed file set may depend on which
    # clang-tidy is installed.  Both bit CI once: the baseline's own entries
    # came back as new findings under Ubuntu's older clang-tidy.
    require_text(path, "def _covered(index, path, names)",
                 "baseline matching is alias-aware, not literal string equality")
    require_text(path, "any(names & recorded",
                 "a renamed or aliased check still matches its baseline entry")
    require_text(path, "--header-filter=",
                 "clang-tidy is told which files to analyze; the default "
                 "differs between clang-tidy versions")
    require_text(path, "SHARD_HEADER_FILTER",
                 "the amalgamated .cpp shards stay inside the analyzed surface")
    require_text(path, "def _merge_baseline",
                 "regenerating the baseline adds findings and only drops "
                 "entries whose source file is gone, so one host cannot delete "
                 "another host's live findings")
    require_text(gates, "static_analysis.run_self_tests()",
                 "the ratchet's own matching rules run in the regression suite")


def _require(condition, message):
    if not condition:
        print(f"Static-analysis self-test FAILED: {message}")
        sys.exit(1)


def run_self_tests():
    """Self-tests for the ratchet's matching rules.

    These are pure and hardware-free on purpose: the rules below decide whether
    a build fails, and they were wrong once already -- a baseline written by
    clang-tidy 22 reported three of its own entries as new findings on CI's
    clang-tidy 18, because the two versions print different alias names for the
    same check.
    """
    script_dir = os.path.join("C:" + os.sep if sys.platform == "win32" else
                              os.sep, "repo")
    new_style = os.path.join(script_dir, "source", "linux_tui_render.cpp")
    old = _parse_diagnostic(
        f"{new_style}:269:9: warning: 'sscanf' used to convert a string to an "
        "integer value [cert-err34-c]", script_dir)
    new = _parse_diagnostic(
        f"{new_style}:269:9: warning: 'sscanf' used to convert a string to an "
        "integer value [bugprone-unchecked-string-to-number-conversion,"
        "cert-err34-c]", script_dir)
    _require(old is not None and new is not None, "diagnostic line not parsed")
    _require(old[0] == "source/linux_tui_render.cpp",
             f"path not made relative and posix: {old[0]}")

    # Either version's baseline must accept the other version's diagnostic.
    from_new = _alias_index([(new[0], new[1])])
    from_old = _alias_index([(old[0], old[1])])
    _require(_covered(from_new, *old),
             "an LLVM 18 diagnostic is not covered by an LLVM 20+ baseline")
    _require(_covered(from_old, *new),
             "an LLVM 20+ diagnostic is not covered by an LLVM 18 baseline")

    # The gate must still bite: a different check, or the same check in another
    # file, is a new finding.
    other_check = (old[0], _alias_set("bugprone-branch-clone"))
    _require(not _covered(from_new, *other_check),
             "an unrelated check was absorbed by an aliased baseline entry")
    other_path = ("source/linux_gpu.cpp", old[1])
    _require(not _covered(from_new, *other_path),
             "a finding in another file matched this file's baseline entry")

    # Line numbers are churn, so two hits of one check in one file collapse.
    second = _parse_diagnostic(
        f"{new_style}:900:1: warning: other text [cert-err34-c]", script_dir)
    _require(_entry_key(*old) == _entry_key(*second),
             "line numbers leaked into the baseline key")

    # Both aliases of a recorded entry are covered, so a host that prints the
    # other name does not report a phantom stale entry.
    baseline_entry = _entry_key(*new)
    parsed = _parse_entry(baseline_entry)
    _require(_covered(_alias_index([old]), *parsed),
             "a baselined alias set was reported stale by an older clang-tidy")

    # Compiler errors are never baseline-eligible, so they must survive parsing
    # of the "error:" severity as a check name run_clang_tidy() can recognize.
    fatal = _parse_diagnostic(
        f"{new_style}:1:1: error: 'cstddef' file not found "
        "[clang-diagnostic-error]", script_dir)
    _require(fatal is not None and "clang-diagnostic-error" in fatal[1],
             "a compiler error is not recognized as never-baseline-eligible")

    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "tidy-baseline.txt")
        _write_baseline(path, {baseline_entry}, "LLVM version 22.1.8")
        _require(_load_baseline(path) == {baseline_entry},
                 "baseline round-trip changed its entries")
        _require(_baseline_generator(path) == "LLVM version 22.1.8",
                 "baseline generator stamp did not round-trip")

        # Regeneration must not delete what this host merely cannot see: the
        # analyzer's coverage differs by version, and the Windows shards are
        # invisible to a Linux run entirely.
        os.makedirs(os.path.join(tmp, "source"))
        live = os.path.join(tmp, "source", "still_here.cpp")
        with open(live, "w", encoding="utf-8") as handle:
            handle.write("// fixture\n")
        unseen = "source/still_here.cpp\tclang-analyzer-optin.taint.TaintedAlloc"
        deleted = "source/removed_shard.cpp\tbugprone-branch-clone"
        fresh = "source/still_here.cpp\tbugprone-branch-clone"
        merged, gone = _merge_baseline({unseen, deleted}, {fresh}, tmp)
        _require(unseen in merged,
                 "regeneration dropped a finding this clang-tidy cannot see")
        _require(fresh in merged, "regeneration did not record a new finding")
        _require(deleted not in merged and gone == {deleted},
                 "regeneration kept an entry whose source file is gone")

    # The header filter decides whether the amalgamated shards are analyzed at
    # all; without it, clang-tidy 18 silently skipped three baselined findings.
    shard_filter = re.compile(SHARD_HEADER_FILTER)
    for shard in ("/repo/source/linux_backend_discovery.cpp",
                  r"C:\repo\source\main_service_persist.cpp",
                  "/repo/tests/regression_main.cpp"):
        _require(shard_filter.search(shard),
                 f"header filter excludes the amalgamated shard {shard}")
    for excluded in ("/repo/source/gpu_core.h", "/usr/include/stdio.h",
                     "/repo/zig/lib/libcxx/include/vector"):
        _require(not shard_filter.search(excluded),
                 f"header filter widened the analyzed surface to {excluded}")


def run_clang_tidy(ctx, write_baseline=False):
    """Run the static-analysis ratchet over host-compatible compile commands."""
    tidy = _host_tidy(ctx)
    if not tidy or not os.path.exists(tidy):
        print("ERROR: clang-tidy is required for --tidy but was not found")
        return 1

    # Regenerate on this host. A Windows database contains PE-only flags, while
    # Linux needs Zig's libc++/glibc include roots.
    ctx.generate_lsp_files()
    database = os.path.join(ctx.SCRIPT_DIR, "compile_commands.json")
    with open(database, "r", encoding="utf-8") as handle:
        entries = _host_entries(ctx, json.load(handle))
    if not entries:
        print("ERROR: no host-compatible clang-tidy compile commands")
        return 1

    tidy_db = ctx.prepare_work_subdir("tidy-database")
    with open(os.path.join(tidy_db, "compile_commands.json"), "w",
              encoding="utf-8", newline="\n") as handle:
        json.dump(entries, handle, indent=2)
        handle.write("\n")
    try:
        extra_args = _windows_extra_args(ctx)
    except RuntimeError as exc:
        print(f"ERROR: {exc}")
        ctx.cleanup_work_subdir(tidy_db)
        return 1

    sources = sorted({entry["file"] for entry in entries})
    host_version = _tidy_version(tidy)
    print(f"Running clang-tidy over {len(sources)} translation unit(s)")
    print(f"  Tool: {tidy} ({host_version})")
    print(f"  Header filter: {SHARD_HEADER_FILTER}")
    findings = []
    execution_failures = []
    try:
        for source in sources:
            result = subprocess.run(
                [tidy, f"-checks={TIDY_CHECKS}", "-quiet",
                 f"--header-filter={SHARD_HEADER_FILTER}",
                 f"-p={tidy_db}", *extra_args, source],
                cwd=ctx.SCRIPT_DIR, text=True, capture_output=True)
            combined = "\n".join(
                part for part in (result.stdout, result.stderr) if part)
            for line in combined.splitlines():
                parsed = _parse_diagnostic(line, ctx.SCRIPT_DIR)
                if parsed:
                    findings.append((*parsed, line.strip()))
            if result.returncode != 0:
                tail = "\n".join(combined.splitlines()[-12:])
                execution_failures.append(
                    f"{os.path.relpath(source, ctx.SCRIPT_DIR)} "
                    f"(exit {result.returncode})\n{tail}")
    finally:
        ctx.cleanup_work_subdir(tidy_db)

    baseline_path = os.path.join(ctx.SCRIPT_DIR, "tidy-baseline.txt")
    baseline = _load_baseline(baseline_path)
    current = {_entry_key(path, names) for path, names, _ in findings}
    source_paths = {
        os.path.relpath(path, ctx.SCRIPT_DIR).replace("\\", "/")
        for path in sources
    }
    baseline_index = _alias_index(_parse_entry(entry) for entry in baseline)
    current_index = _alias_index((path, names) for path, names, _ in findings)
    if write_baseline:
        # A regeneration only ever adds.  What a run can see depends on the
        # platform (a Linux host analyzes no Win32 shard) *and* on the
        # clang-tidy version: LLVM 22 reports a tainted-alloc in
        # linux_daemon_transport.cpp that LLVM 18 does not.  Pruning everything
        # this host failed to report would therefore delete live findings and
        # hand the other host a build failure over a finding it always had.
        # Retiring a fixed finding stays a deliberate one-line deletion, and a
        # premature one fails loudly on the next run instead of silently.
        merged, gone = _merge_baseline(baseline, current, ctx.SCRIPT_DIR)
        _write_baseline(baseline_path, merged, host_version)
        print(f"Wrote {len(merged)} baseline entries to {baseline_path}")
        recorded = sorted(
            key for key in current
            if not _covered(baseline_index, *_parse_entry(key))
        )
        for key in recorded:
            print(f"  recorded: {key}")
        for key in sorted(gone):
            print(f"  dropped (source file no longer exists): {key}")
        return 1 if execution_failures else 0

    by_check = {}
    for _, names, _ in findings:
        check = ",".join(sorted(names))
        by_check[check] = by_check.get(check, 0) + 1
    if by_check:
        print("clang-tidy findings by check:")
        for check, count in sorted(
                by_check.items(), key=lambda item: (-item[1], item[0])):
            print(f"  {count:5d}  {check}")

    new_findings = [
        line for path, names, line in findings
        if not _covered(baseline_index, path, names)
    ]
    if new_findings:
        print(f"clang-tidy: {len(new_findings)} finding(s) not in the baseline:")
        for line in new_findings[:50]:
            print(f"  {line}")
        if len(new_findings) > 50:
            print(f"  ... and {len(new_findings) - 50} more")
        # A baseline written by another clang-tidy is the first thing to rule
        # out: renamed checks and version-only findings both land here.
        baseline_version = _baseline_generator(baseline_path)
        if baseline_version != host_version:
            print(f"  note: baseline was generated by {baseline_version}; "
                  f"this host runs {host_version}")
    else:
        print(f"clang-tidy: no new findings ({len(baseline)} baselined)")

    stale = sorted(
        entry for entry in baseline
        if not _covered(current_index, *_parse_entry(entry))
    )
    if sys.platform != "win32":
        stale = [
            key for key in stale
            if key.split("\t", 1)[0].startswith("source/linux_")
            or key.split("\t", 1)[0] in source_paths
        ]
    if stale:
        # Advisory only, and deliberately not actionable by --tidy-baseline: an
        # entry can be missing here because the finding was fixed, or merely
        # because this clang-tidy is not the one that reported it.
        print(f"clang-tidy: {len(stale)} baselined finding(s) not reported by "
              f"{host_version}; delete the line by hand once the finding is "
              "confirmed fixed on every host")
        for key in stale:
            print(f"  {key}")
    if execution_failures:
        print(f"clang-tidy: {len(execution_failures)} execution failure(s):")
        for failure in execution_failures:
            print(f"  {failure}")
    diagnostic_errors = [
        line for _, names, line in findings
        if "clang-diagnostic-error" in names
    ]
    if diagnostic_errors:
        print("clang-tidy: compiler diagnostics are never baseline-eligible")
    return 1 if new_findings or execution_failures or diagnostic_errors else 0
