// SPDX-FileCopyrightText: Copyright (c) 2026 aufkrawall
// SPDX-License-Identifier: MIT

#ifndef GREEN_CURVE_GUI_TRAY_CALLBACK_POLICY_H
#define GREEN_CURVE_GUI_TRAY_CALLBACK_POLICY_H

// Shell notification version 4 reports activation through NIN_SELECT /
// NIN_KEYSELECT.  Treating the legacy mouse-up notifications as activation as
// well can turn one physical click into two window-open transactions.
enum GuiTrayCallbackKind {
    GUI_TRAY_CALLBACK_UNKNOWN = 0,
    GUI_TRAY_CALLBACK_LEGACY_PRIMARY_UP,
    GUI_TRAY_CALLBACK_LEGACY_PRIMARY_DOUBLE,
    GUI_TRAY_CALLBACK_LEGACY_CONTEXT,
    GUI_TRAY_CALLBACK_V4_SELECT,
    GUI_TRAY_CALLBACK_V4_KEY_SELECT,
    GUI_TRAY_CALLBACK_V4_CONTEXT,
};

static inline bool gui_tray_callback_opens_window(bool version4,
    GuiTrayCallbackKind kind) {
    if (version4) {
        return kind == GUI_TRAY_CALLBACK_V4_SELECT ||
            kind == GUI_TRAY_CALLBACK_V4_KEY_SELECT;
    }
    return kind == GUI_TRAY_CALLBACK_LEGACY_PRIMARY_UP ||
        kind == GUI_TRAY_CALLBACK_LEGACY_PRIMARY_DOUBLE;
}

static inline bool gui_tray_callback_opens_context_menu(bool version4,
    GuiTrayCallbackKind kind) {
    return version4 ? kind == GUI_TRAY_CALLBACK_V4_CONTEXT
                    : kind == GUI_TRAY_CALLBACK_LEGACY_CONTEXT;
}

// Display-driver reconstruction can ask Windows to show a top-level window
// without any Green Curve tray callback.  A durable hidden intent, rather than
// the transient WS_VISIBLE bit, decides whether that unsolicited show is
// allowed.  Explicit tray/single-instance activation clears the intent before
// requesting visibility.
static inline bool gui_tray_hidden_intent_blocks_show(
    bool hiddenIntent, bool showRequested) {
    return hiddenIntent && showRequested;
}

// SWP_SHOWWINDOW is not the only route by which Windows can restore the
// WS_VISIBLE state while rebuilding a display device.  Once visibility has
// changed, the durable hidden intent remains authoritative.  The active flag
// prevents the corrective SW_HIDE from recursively enforcing itself through
// the nested window messages generated by ShowWindow.
static inline bool gui_tray_hidden_intent_requires_rehide(
    bool hiddenIntent, bool windowVisible, bool enforcementActive) {
    return hiddenIntent && windowVisible && !enforcementActive;
}

#endif // GREEN_CURVE_GUI_TRAY_CALLBACK_POLICY_H
