// SPDX-FileCopyrightText: Copyright (c) 2026 aufkrawall
// SPDX-License-Identifier: MIT

#include "linux_port_internal.h"
#include "linux_gpu.h"
#include "linux_daemon.h"
#include "linux_backend.h"
#include "linux_crash_breadcrumb.h"
#include "linux_crash_report.h"
#include "linux_debug_log.h"
#include "linux_terminal_launch.h"
#include "linux_startup_sync.h"

#include <ctype.h>
#include <errno.h>
#include <glob.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <unistd.h>
#include <vector>

static bool read_small_file(const char* path, std::string* out, size_t maxBytes) {
    out->clear();
    FILE* file = fopen(path, "rb");
    if (!file) return false;
    std::vector<char> buffer(maxBytes + 1u, 0);
    size_t readCount = fread(buffer.data(), 1, maxBytes, file);
    fclose(file);
    out->assign(buffer.data(), readCount);
    return true;
}

static std::string shell_quote_single(const char* text) {
    std::string out;
    out.push_back('\'');
    if (text) {
        for (const char* p = text; *p; ++p) {
            if (*p == '\'') out += "'\"'\"'";
            else out.push_back(*p);
        }
    }
    out.push_back('\'');
    return out;
}

static std::string capture_command_output(const char* command, size_t maxBytes) {
    std::string output;
    // flawfinder: ignore -- selected only from fixed probe constants; output is bounded.
    FILE* pipe = popen(command, "r");
    if (!pipe) {
        appendf(&output, "command failed to start: %s\n", command);
        return output;
    }

    char buffer[512] = {};
    while (output.size() < maxBytes) {
        size_t toRead = sizeof(buffer);
        if (output.size() + toRead > maxBytes) toRead = maxBytes - output.size();
        size_t readCount = fread(buffer, 1, toRead, pipe);
        if (readCount > 0) output.append(buffer, readCount);
        if (readCount < toRead) break;
    }
    pclose(pipe);
    if (output.empty()) output = "<no output>\n";
    return output;
}

static void append_code_block(std::string* report, const char* title, const std::string& body) {
    appendf(report, "### %s\n\n```text\n", title);
    report->append(body);
    if (report->empty() || report->back() != '\n') report->push_back('\n');
    report->append("```\n\n");
}

static void append_path_state(std::string* report, const char* path) {
    struct stat st = {};
    if (stat(path, &st) == 0) {
        appendf(report, "- `%s`: present", path);
        if (S_ISDIR(st.st_mode)) report->append(" (directory)\n");
        else if (S_ISCHR(st.st_mode)) report->append(" (char device)\n");
        else if (S_ISREG(st.st_mode)) report->append(" (regular file)\n");
        else report->append("\n");
    } else {
        appendf(report, "- `%s`: missing\n", path);
    }
}

bool run_linux_probe(const char* outputPath, ProbeSummary* summary, char* err, size_t errSize) {
    if (summary) memset(summary, 0, sizeof(*summary));

    char resolvedOutput[LINUX_PATH_MAX] = {};
    if (outputPath && *outputPath) {
        snprintf(resolvedOutput, sizeof(resolvedOutput), "%s", outputPath);
    } else {
        default_probe_output_path(nullptr, resolvedOutput, sizeof(resolvedOutput));
    }

    std::string report;
    appendf(&report, "# Green Curve Linux Probe\n\n");
    appendf(&report, "Generated by %s %s on native Linux.\n\n", APP_NAME, APP_VERSION);

    const char* sessionType = getenv("XDG_SESSION_TYPE");
    const char* currentDesktop = getenv("XDG_CURRENT_DESKTOP");
    const char* waylandDisplay = getenv("WAYLAND_DISPLAY");
    const char* xDisplay = getenv("DISPLAY");
    bool isRoot = geteuid() == 0;
    bool hasWayland = (sessionType && streqi_ascii(sessionType, "wayland")) || (waylandDisplay && *waylandDisplay);

    if (summary) {
        summary->completed = true;
        summary->isRoot = isRoot;
        summary->hasWayland = hasWayland;
        summary->hasDisplay = xDisplay && *xDisplay;
        summary->hasNvidiaSmi = linux_command_available("nvidia-smi");
        summary->hasSystemctl = linux_command_available("systemctl");
        summary->hasSudo = linux_command_available("sudo");
        summary->hasPkexec = linux_command_available("pkexec");
        snprintf(summary->sessionType, sizeof(summary->sessionType), "%s", sessionType ? sessionType : "unknown");
        snprintf(summary->currentDesktop, sizeof(summary->currentDesktop), "%s", currentDesktop ? currentDesktop : "unknown");
        snprintf(summary->reportPath, sizeof(summary->reportPath), "%s", resolvedOutput);
        snprintf(summary->summary, sizeof(summary->summary), "root=%s, wayland=%s, nvidia-smi=%s, systemctl=%s",
            isRoot ? "yes" : "no",
            hasWayland ? "yes" : "no",
            summary->hasNvidiaSmi ? "yes" : "no",
            summary->hasSystemctl ? "yes" : "no");
    }

    appendf(&report, "## Session\n\n");
    appendf(&report, "- Effective UID: `%d`\n", (int)geteuid());
    appendf(&report, "- Root: `%s`\n", isRoot ? "yes" : "no");
    appendf(&report, "- XDG_SESSION_TYPE: `%s`\n", sessionType ? sessionType : "unset");
    appendf(&report, "- WAYLAND_DISPLAY: `%s`\n", waylandDisplay ? waylandDisplay : "unset");
    appendf(&report, "- DISPLAY: `%s`\n", xDisplay ? xDisplay : "unset");
    appendf(&report, "- XDG_CURRENT_DESKTOP: `%s`\n", currentDesktop ? currentDesktop : "unset");
    appendf(&report, "- TERM: `%s`\n\n", getenv("TERM") ? getenv("TERM") : "unset");

    appendf(&report, "## Tools\n\n");
    appendf(&report, "- `nvidia-smi`: `%s`\n", linux_command_available("nvidia-smi") ? "yes" : "no");
    appendf(&report, "- `systemctl`: `%s`\n", linux_command_available("systemctl") ? "yes" : "no");
    appendf(&report, "- `sudo`: `%s`\n", linux_command_available("sudo") ? "yes" : "no");
    appendf(&report, "- `pkexec`: `%s`\n", linux_command_available("pkexec") ? "yes" : "no");
    appendf(&report, "- `journalctl`: `%s`\n", linux_command_available("journalctl") ? "yes" : "no");
    appendf(&report, "- `modinfo`: `%s`\n", linux_command_available("modinfo") ? "yes" : "no");
    appendf(&report, "- `lspci`: `%s`\n\n", linux_command_available("lspci") ? "yes" : "no");

    appendf(&report, "## Paths\n\n");
    append_path_state(&report, "/dev/nvidiactl");
    append_path_state(&report, "/dev/nvidia0");
    append_path_state(&report, "/dev/nvidia-uvm");
    append_path_state(&report, "/proc/driver/nvidia/version");
    append_path_state(&report, "/sys/module/nvidia/version");
    append_path_state(&report, "/sys/kernel/debug");
    append_path_state(&report, "/sys/class/drm");
    append_path_state(&report, "/sys/class/hwmon");
    struct stat daemonSocketStatus = {};
    if (lstat(GC_DAEMON_SOCKET_PATH, &daemonSocketStatus) == 0) {
        appendf(&report,
            "- Daemon socket pathname: type=`%s`, uid=`%lu`, gid=`%lu`, mode=`%04o`\n",
            S_ISSOCK(daemonSocketStatus.st_mode) ? "socket" : "unexpected",
            (unsigned long)daemonSocketStatus.st_uid,
            (unsigned long)daemonSocketStatus.st_gid,
            (unsigned int)(daemonSocketStatus.st_mode & 0777));
    } else {
        appendf(&report, "- Daemon socket pathname: unavailable (`%s`)\n",
                strerror(errno));
    }
    report.push_back('\n');

    appendf(&report, "## Diagnostics\n\n");
    appendf(&report, "- Debug log: `%s`\n",
            linux_debug_log_path()[0] ? linux_debug_log_path()
                                      : "disabled ([debug] enabled=0)");
    appendf(&report, "- Crash report: `%s` (carries its own symbolize command)\n",
            linux_crash_report_path()[0] ? linux_crash_report_path() : "not armed");
    // Green Curve writes a text report, not a dump: the real core file is
    // produced by the kernel, so where it lands is the first thing to check
    // when a crash needs post-mortem analysis.
    std::string corePattern;
    if (read_small_file("/proc/sys/kernel/core_pattern", &corePattern, 512)) {
        while (!corePattern.empty() &&
               (corePattern.back() == '\n' || corePattern.back() == '\r'))
            corePattern.pop_back();
        appendf(&report, "- Kernel core_pattern: `%s`\n", corePattern.c_str());
        bool systemdCoredump = corePattern.find("systemd-coredump") != std::string::npos;
        appendf(&report, "- Core dumps: %s\n", systemdCoredump
            ? "captured by systemd-coredump; list them with `coredumpctl list greencurve`"
            : "written per the pattern above (see `ulimit -c`)");
    }
    appendf(&report, "- `coredumpctl`: `%s`\n\n",
            linux_command_available("coredumpctl") ? "yes" : "no");

    struct utsname systemName = {};
    if (uname(&systemName) == 0) {
        std::string unameText;
        appendf(&unameText, "%s %s %s %s %s\n", systemName.sysname, systemName.nodename, systemName.release, systemName.version, systemName.machine);
        append_code_block(&report, "uname -a", unameText);
    }

    append_code_block(&report, "id", capture_command_output("id", 4096));
    if (linux_command_available("lsmod")) append_code_block(&report, "lsmod | grep nvidia", capture_command_output("lsmod | grep -i nvidia", 8192));
    if (linux_command_available("lspci")) append_code_block(&report, "lspci | grep -i nvidia", capture_command_output("lspci -nn | grep -i nvidia", 8192));
    if (linux_command_available("modinfo")) append_code_block(&report, "modinfo nvidia", capture_command_output("modinfo nvidia", 16384));
    if (linux_command_available("nvidia-smi")) {
        append_code_block(&report, "nvidia-smi -L", capture_command_output("nvidia-smi -L", 8192));
        append_code_block(&report, "nvidia-smi -q -d POWER,CLOCK,FAN,PERFORMANCE", capture_command_output("nvidia-smi -q -d POWER,CLOCK,FAN,PERFORMANCE", 32768));
    }

    std::string procVersion;
    if (read_small_file("/proc/driver/nvidia/version", &procVersion, 4096)) {
        append_code_block(&report, "/proc/driver/nvidia/version", procVersion);
    }

    glob_t gpuInfo = {};
    if (glob("/proc/driver/nvidia/gpus/*/information", 0, nullptr, &gpuInfo) == 0) {
        for (size_t i = 0; i < gpuInfo.gl_pathc; i++) {
            std::string content;
            if (read_small_file(gpuInfo.gl_pathv[i], &content, 8192)) {
                append_code_block(&report, gpuInfo.gl_pathv[i], content);
            }
        }
    }
    globfree(&gpuInfo);

    appendf(&report, "## Backend Binding and VF Health (read-only)\n\n");
    LinuxGpuState backend = {};
    char backendError[256] = {};
    bool backendReady = linux_backend_init(
        &backend, nullptr, backendError, sizeof(backendError));
    appendf(&report, "- NVML backend ready: `%s`\n",
            backendReady ? "yes" : "no");
    appendf(&report, "- GPU: `%s`\n",
            backend.gpuName[0] ? backend.gpuName : "unavailable");
    appendf(&report, "- Family: `%d`\n", (int)backend.family);
    appendf(&report, "- Match method: `%s`\n",
            linux_gpu_match_method_name(backend.nvapiMatchMethod));
    appendf(&report, "- Architecture source: `%s`\n",
            linux_gpu_architecture_source_name(backend.architectureSource));
    appendf(&report,
            "- Driver statuses: info=`%d`, status=`%d`, control=`%d`\n",
            backend.vfInfoStatus, backend.vfStatusStatus,
            backend.vfControlStatus);
    appendf(&report, "- VF snapshot fresh: `%s` (%d points)\n",
            backend.vfSnapshotFresh ? "yes" : "no",
            backend.numPopulated);
    appendf(&report, "- Health: `%s` (driver status `%d`)\n",
            service_gpu_health_reason_name(backend.health.reason),
            backend.health.driverStatus);
    appendf(&report, "- Detail: `%s`\n",
            backend.health.detail[0] ? backend.health.detail :
            (backendError[0] ? backendError : "none"));
    if (backend.nvmlLib || backend.nvapiLib)
        linux_backend_shutdown(&backend);

    ServiceResponse daemonState = {};
    char daemonError[256] = {};
    bool daemonOnline = linux_daemon_get_state(
        nullptr, &daemonState, daemonError, sizeof(daemonError));
    appendf(&report, "\n## Daemon Protocol and Published Health\n\n");
    appendf(&report, "- Reachable as this user: `%s`\n",
            daemonOnline ? "yes" : "no");
    if (daemonOnline) {
        appendf(&report,
            "- Version/build/protocol/PID: `%s` / `%u` / `%u` / `%u`\n",
            daemonState.serviceVersion, daemonState.serviceBuildNumber,
            daemonState.version, daemonState.servicePid);
        appendf(&report,
            "- Phase: `%u`; VF fresh: `%s`; domains: `0x%02x`\n",
            daemonState.state.gpuPhase,
            daemonState.snapshot.health.vfSnapshotFresh ? "yes" : "no",
            daemonState.snapshot.health.availableMutationDomains);
        appendf(&report, "- Health: `%s` (status `%d`) — `%s`\n",
            service_gpu_health_reason_name(
                daemonState.snapshot.health.reason),
            daemonState.snapshot.health.driverStatus,
            daemonState.snapshot.health.detail[0]
                ? daemonState.snapshot.health.detail : "none");
    } else {
        appendf(&report, "- Connection detail: `%s`\n",
            daemonError[0] ? daemonError : "unknown daemon error");
    }
    report.push_back('\n');

    appendf(&report, "## Library Candidates\n\n");
    const char* libraryPatterns[] = {
        "/usr/lib*/libnvidia-ml.so*",
        "/usr/lib*/nvidia*/libnvidia-ml.so*",
        "/usr/lib*/libnvidia-api.so*",
        "/usr/lib*/nvidia*/libnvidia-api.so*",
        "/usr/lib*/libXNVCtrl.so*",
        "/usr/lib*/nvidia*/libXNVCtrl.so*",
    };
    for (size_t patternIndex = 0; patternIndex < ARRAY_COUNT(libraryPatterns); patternIndex++) {
        glob_t libraries = {};
        if (glob(libraryPatterns[patternIndex], 0, nullptr, &libraries) == 0 && libraries.gl_pathc > 0) {
            appendf(&report, "- Pattern `%s`:\n", libraryPatterns[patternIndex]);
            for (size_t pathIndex = 0; pathIndex < libraries.gl_pathc && pathIndex < 8; pathIndex++) {
                appendf(&report, "  - `%s`\n", libraries.gl_pathv[pathIndex]);
            }
        }
        globfree(&libraries);
    }
    report.push_back('\n');

    appendf(&report, "## Runtime Validation\n\n");
    appendf(&report, "- Run `greencurve --probe` and confirm the console-side native probe reports both NVML and NvAPI available.\n");
    appendf(&report, "- Run `greencurve --self-test` before first apply on a new architecture; it validates the read/write struct path without changing GPU state.\n");
    appendf(&report, "- Install the daemon with `sudo greencurve --service-install`; client apply/reset commands require the daemon socket.\n");
    appendf(&report, "- On unrecognized future GPU families, keep the fallback-warning output and attach this probe report when validating the new architecture.\n");

    if (!write_text_file_atomic(resolvedOutput, report, err, errSize)) return false;
    return true;
}

bool write_linux_assets(const char* outputDir, const char* execPath, const char* configPath, char* err, size_t errSize) {
    if (!outputDir || !*outputDir || !execPath || !*execPath || !configPath || !*configPath) {
        set_message(err, errSize, "Missing asset generation paths");
        return false;
    }
    if (!ensure_directory_recursive(outputDir, err, errSize)) return false;

    std::string execShell = shell_quote_single(execPath);
    std::string configShell = shell_quote_single(configPath);
    // --from-desktop keeps the window open long enough to read an error; on a
    // clean quit the terminal closes immediately, which is what a launcher
    // should do.
    std::string desktopExec = "sh -lc \"exec " + execShell +
        " --tui --from-desktop --config " + configShell + "\"";
    std::string serviceExec = "/bin/sh -lc \"exec " + execShell + " --apply-config --config " + configShell + "\"";

    std::string desktop;
    appendf(&desktop,
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Version=1.0\n"
        "Name=%s\n"
        "Comment=Open the Linux terminal UI for %s\n"
        "Exec=%s\n"
        "Terminal=true\n"
        "Categories=Utility;System;\n"
        "StartupNotify=false\n",
        APP_NAME,
        APP_NAME,
        desktopExec.c_str());

    std::string autostart = desktop;
    autostart += "X-GNOME-Autostart-enabled=true\n";

    std::string service;
    appendf(&service,
        "[Unit]\n"
        "Description=%s one-shot profile apply via daemon\n"
        "After=greencurve.service\n"
        "Requires=greencurve.service\n"
        "ConditionPathExists=%s\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        "ExecStart=%s\n"
        "StandardOutput=journal\n"
        "StandardError=journal\n\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n",
        APP_NAME,
        configPath,
        serviceExec.c_str());

    std::string readme;
    appendf(&readme,
        "# Linux Assets\n\n"
        "These files were generated by %s %s.\n\n"
        "- `greencurve.desktop`: visible launcher with `Terminal=true` for GNOME/KDE/Wayland sessions\n"
        "- `greencurve-autostart.desktop`: session autostart launcher that still opens a terminal window\n"
        "- `greencurve-apply.service`: optional one-shot profile apply client that requires the real `greencurve.service` daemon\n\n"
        "The release archive also ships `greencurve-setup.sh`, which performs the\n"
        "install, group enrollment and desktop entry in one step:\n\n"
        "```bash\n"
        "sudo ./greencurve-setup.sh install\n"
        "./greencurve-setup.sh status\n"
        "```\n\n"
        "Manual equivalent:\n\n"
        "```bash\n"
        "install -Dm644 greencurve.desktop ~/.local/share/applications/greencurve.desktop\n"
        "install -Dm644 greencurve-autostart.desktop ~/.config/autostart/greencurve.desktop\n"
        "sudo %s --service-install\n"
        "sudo usermod -aG greencurve \"$USER\"\n"
        "# Sign out/in, or run: newgrp greencurve\n"
        "sudo install -Dm644 greencurve-apply.service /etc/systemd/system/greencurve-apply.service\n"
        "sudo systemctl daemon-reload\n"
        "sudo systemctl enable greencurve-apply.service\n"
        "```\n\n"
        "The generated one-shot unit is only a convenience hook; normal live control uses the daemon installed by `--service-install`.\n",
        APP_NAME,
        APP_VERSION,
        execShell.c_str());

    std::string desktopPath = path_join(outputDir, "greencurve.desktop");
    std::string autostartPath = path_join(outputDir, "greencurve-autostart.desktop");
    std::string servicePath = path_join(outputDir, "greencurve-apply.service");
    std::string readmePath = path_join(outputDir, "README.md");

    if (!write_text_file_atomic(desktopPath.c_str(), desktop, err, errSize)) return false;
    if (!write_text_file_atomic(autostartPath.c_str(), autostart, err, errSize)) return false;
    if (!write_text_file_atomic(servicePath.c_str(), service, err, errSize)) return false;
    if (!write_text_file_atomic(readmePath.c_str(), readme, err, errSize)) return false;
    return true;
}

int main(int argc, char** argv) {
    // Installed before any parsing or driver work so an early failure is still
    // diagnosable.  Writes a journal breadcrumb and then re-raises; it never
    // suppresses the crash.
    linux_install_crash_breadcrumbs("cli");
    LinuxCliOptions opts = {};
    if (!parse_linux_cli_options(argc, argv, &opts)) {
        fprintf(stderr, "%s\n", opts.error[0] ? opts.error : "Failed to parse CLI");
        return 1;
    }

    if (opts.showHelp) {
        print_linux_help();
        return 0;
    }

    char configPath[LINUX_PATH_MAX] = {};
    if (opts.hasConfigPath) snprintf(configPath, sizeof(configPath), "%s", opts.configPath);
    else if (!default_linux_config_path(configPath, sizeof(configPath))) snprintf(configPath, sizeof(configPath), "%s", CONFIG_FILE_NAME);

    // Debug logging is configured before any GPU, daemon or terminal work so an
    // early failure is still recorded.  The daemon logs into its writable state
    // directory and mirrors to the journal; clients log next to config.ini and
    // keep stderr clean for the terminal UI.
    const char* debugRole = opts.daemon ? "daemon"
        : (opts.tui || !opts.recognized) ? "tui" : "cli";
    linux_debug_log_set_enabled(linux_debug_log_enabled_for(
        getenv(LINUX_DEBUG_LOG_ENV),
        load_linux_debug_enabled(configPath, LINUX_DEBUG_DEFAULT_ENABLED)));
    linux_debug_log_set_stderr_mirror(opts.daemon);
    linux_debug_log_configure(configPath, opts.daemon, debugRole);
    // A fatal signal now leaves its breadcrumb in the log file as well as on
    // stderr, which is the only copy a desktop-launched client ever has.
    linux_set_crash_log_fd(linux_debug_log_raw_fd());
    // ...and in a crash report next to config.ini.  Only the path is published;
    // the file is created by the handler if and only if a crash writes to it,
    // so a normal run leaves nothing behind (linux_crash_breadcrumb.h).  One
    // call arms the whole program, the daemon role included.
    linux_crash_report_configure(configPath, opts.daemon);
    linux_set_crash_report_path(linux_crash_report_path());
    // Group membership and socket permissions are the most common reason a
    // client cannot reach the daemon, so they are recorded up front rather than
    // only when a request happens to fail.
    if (!opts.daemon && linux_debug_log_is_enabled())
        linux_daemon_log_client_environment();
    linux_debug_logf("cli: argc=%d role=%s recognized=%d applyConfig=%d "
                     "saveConfig=%d probe=%d selfTest=%d serviceInstall=%d "
                     "serviceRemove=%d startupPolicy=%d resumeRestore=%d",
                     argc, debugRole, opts.recognized ? 1 : 0,
                     opts.applyConfig ? 1 : 0, opts.saveConfig ? 1 : 0,
                     opts.probe ? 1 : 0, opts.selfTest ? 1 : 0,
                     opts.serviceInstall ? 1 : 0, opts.serviceRemove ? 1 : 0,
                     (int)opts.startupPolicyAction,
                     opts.resumeRestore ? 1 : 0);

    GpuAdapterInfo gpuTarget = {};
    if (opts.hasGpuTarget) {
        gpuTarget = opts.gpuTarget;
    } else {
        load_linux_gpu_selection(configPath, &gpuTarget);
    }

    if (opts.dumpLive || opts.jsonLive) {
        ServiceResponse live = {};
        char liveErr[256] = {};
        if (!linux_daemon_get_state(gpuTarget.valid ? &gpuTarget : nullptr,
                                    &live, liveErr, sizeof(liveErr))) {
            fprintf(stderr, "Cannot read live GPU state: %s\n",
                    liveErr[0] ? liveErr : "daemon request failed");
            return 1;
        }
        if (opts.dumpLive) print_linux_live_state_text(stdout, &live);
        if (opts.jsonLive) print_linux_live_state_json(stdout, &live);
        return 0;
    }

    // Privileged daemon role (run by systemd as root): owns the GPU and serves
    // the Unix-socket protocol.  Must run before profile loading.
    if (opts.daemon) {
        return linux_daemon_run(configPath);
    }

    // The resume edge.  Nothing about the caller's config takes part: the
    // settings being restored are the ones the daemon is already holding.
    // Both outcomes are printed because the unit is StandardOutput=journal, and
    // a restore that silently did nothing is the failure mode that would
    // otherwise stay invisible until the user noticed stock clocks.
    if (opts.resumeRestore) {
        char message[256] = {};
        bool ok = linux_daemon_resume_restore(message, sizeof(message));
        fprintf(ok ? stdout : stderr, "Resume restore%s: %s\n",
                ok ? "" : " failed",
                message[0] ? message : (ok ? "OK" : "daemon request failed"));
        return ok ? 0 : 1;
    }

    if (opts.selfTest) {
        // In-process read-only validation of the NvAPI/NVML control surfaces on
        // this driver/arch (the arm64 pre-flight). Does not touch the daemon and
        // does not modify GPU state.
        LinuxGpuState gpu;
        char initErr[256] = {};
        if (!linux_backend_init(&gpu, gpuTarget.valid ? &gpuTarget : nullptr, initErr, sizeof(initErr))) {
            fprintf(stderr, "self-test: cannot initialize GPU backend: %s\n",
                    initErr[0] ? initErr : "unknown error");
            return 1;
        }
        bool pass = linux_backend_self_test(&gpu, stdout);
        linux_backend_shutdown(&gpu);
        return pass ? 0 : 2;
    }

    if (opts.serviceInstall || opts.serviceRemove) {
        char svcErr[256] = {};
        ServiceResponse verifiedDaemon = {};
        int rc = opts.serviceInstall
            ? linux_service_install(svcErr, sizeof(svcErr), &verifiedDaemon)
            : linux_service_remove(svcErr, sizeof(svcErr));
        if (rc != 0) {
            fprintf(stderr, "%s\n", svcErr[0] ? svcErr : "service operation failed");
            return rc;
        }
        if (opts.serviceInstall) {
            // The group paragraph is decided, not assumed: printing "add your
            // user" to someone who is already enrolled -- or to someone whose
            // enrollment greencurve-setup.sh is about to perform on the very
            // next line -- sends them chasing a non-problem.
            char groupAdvice[512] = {};
            linux_describe_group_enrollment(groupAdvice, sizeof(groupAdvice));
            printf(
                "Green Curve daemon installed, restarted, and verified "
                "(version %s, build %u, protocol %u, pid %u).\n"
                "The daemon socket pathname was verified root:greencurve mode=0660.\n"
                "%s",
                verifiedDaemon.serviceVersion,
                verifiedDaemon.serviceBuildNumber,
                verifiedDaemon.version,
                verifiedDaemon.servicePid,
                groupAdvice);
            if (verifiedDaemon.state.gpuPhase != SERVICE_GPU_PHASE_READY) {
                const ServiceGpuHealth& health = verifiedDaemon.snapshot.health;
                fprintf(stderr,
                    "Warning: daemon protocol is healthy, but GPU state is degraded: %s%s%s "
                    "(available mutation domains=0x%02x).\n",
                    service_gpu_health_reason_name(health.reason),
                    health.detail[0] ? " — " : "", health.detail,
                    health.availableMutationDomains);
            }
        } else {
            printf("Green Curve daemon removed.\n");
        }
        return 0;
    }

    if (opts.hasGpuTarget) {
        ServiceSnapshot snapshot = {};
        char selectionErr[256] = {};
        if (!linux_daemon_snapshot(&snapshot, selectionErr, sizeof(selectionErr))) {
            fprintf(stderr, "Cannot validate GPU selection: %s\n", selectionErr);
            return 1;
        }
        int match = -1;
        for (unsigned int i = 0; i < snapshot.adapterCount; ++i) {
            const GpuAdapterInfo& adapter = snapshot.adapters[i];
            if (!adapter.valid || adapter.pciDomain != gpuTarget.pciDomain ||
                adapter.pciBus != gpuTarget.pciBus || adapter.pciDevice != gpuTarget.pciDevice ||
                adapter.pciFunction != gpuTarget.pciFunction)
                continue;
            if (match >= 0) { match = -2; break; }
            match = (int)i;
        }
        if (match < 0 || !snapshot.adapters[match].pciInfoValid) {
            fprintf(stderr, "Cannot validate GPU selection: exact BDF/PCI identity is %s\n",
                    match == -2 ? "ambiguous" : "not available");
            return 1;
        }
        gpuTarget = snapshot.adapters[match];
        if (!save_linux_gpu_selection(configPath, &gpuTarget, selectionErr, sizeof(selectionErr))) {
            fprintf(stderr, "Cannot persist GPU selection: %s\n", selectionErr);
            return 1;
        }
    }

    int slot = opts.hasProfileSlot ? opts.profileSlot : CONFIG_DEFAULT_SLOT;
    DesiredSettings desired = {};
    char err[256] = {};
    if (!load_default_or_selected_profile(configPath, &slot, &desired, err, sizeof(err))) {
        fprintf(stderr, "%s\n", err[0] ? err : "Failed to load config");
        return 1;
    }

    if (opts.reset) {
        initialize_desired_settings_defaults(&desired);
    }
    merge_desired_settings(&desired, &opts.desired);
    normalize_desired_settings_for_ui(&desired);

    if (opts.probe) {
        char outputPath[LINUX_PATH_MAX] = {};
        if (opts.hasProbeOutputPath) snprintf(outputPath, sizeof(outputPath), "%s", opts.probeOutputPath);
        else default_probe_output_path(configPath, outputPath, sizeof(outputPath));
        ProbeSummary summary = {};
        if (!run_linux_probe(outputPath, &summary, err, sizeof(err))) {
            fprintf(stderr, "%s\n", err[0] ? err : "Probe failed");
            return 1;
        }
        printf("Probe written to %s\n", outputPath);
        printf("%s\n", summary.summary);
        // Native driver probe: load NVML + NvAPI (libnvidia-api.so.1) and report
        // the read-only control surfaces (GPU enumeration, family, OC offset
        // range).  Proves the Linux VF-curve path before any write is attempted.
        printf("\n");
        linux_gpu_probe(stdout, nullptr);
    }

    if (opts.writeAssets) {
        char outputDir[LINUX_PATH_MAX] = {};
        char exePath[LINUX_PATH_MAX] = {};
        if (opts.hasAssetsDir) snprintf(outputDir, sizeof(outputDir), "%s", opts.assetsDir);
        else default_assets_output_dir(configPath, outputDir, sizeof(outputDir));
        if (!get_executable_path(exePath, sizeof(exePath))) {
            fprintf(stderr, "Failed to resolve /proc/self/exe\n");
            return 1;
        }
        if (!write_linux_assets(outputDir, exePath, configPath, err, sizeof(err))) {
            fprintf(stderr, "%s\n", err[0] ? err : "Asset generation failed");
            return 1;
        }
        printf("Linux assets written to %s\n", outputDir);
    }

    if (opts.saveConfig) {
        int targetSlot = opts.hasProfileSlot ? opts.profileSlot : slot;
        if (!save_profile_to_config_path(configPath, targetSlot, &desired, err, sizeof(err))) {
            fprintf(stderr, "%s\n", err[0] ? err : "Profile save failed");
            return 1;
        }
        printf("Profile %d written to %s\n", targetSlot, configPath);
        // The daemon holds its own snapshot of a boot-applied profile and
        // cannot read this file, so writing the slot is only half the update.
        ServiceResponse policy = {};
        char policyErr[256] = {};
        bool policyKnown = linux_daemon_get_startup_policy(&policy, policyErr,
                                                           sizeof(policyErr));
        if (!policyKnown) {
            printf("Note: the daemon is unreachable, so a boot-apply snapshot "
                   "of this profile (if configured) still holds the previous "
                   "values.\n");
        } else {
            LinuxStartupSyncResult sync = linux_startup_sync_after_profile_write(
                configPath, targetSlot, true, true,
                policy.state.startupPolicyMode, policy.state.startupPolicySlot);
            if (sync.action != STARTUP_SNAPSHOT_SYNC_NONE) {
                printf("%s%s\n", sync.ok ? "" : "WARNING: ", sync.message);
                if (!sync.ok) return 1;
            }
        }
    }

    if (opts.startupPolicyAction == LINUX_STARTUP_POLICY_ACTION_SHOW) {
        ServiceResponse policy = {};
        char policyErr[256] = {};
        if (!linux_daemon_get_startup_policy(&policy, policyErr, sizeof(policyErr))) {
            fprintf(stderr, "Cannot read the startup policy: %s\n",
                    policyErr[0] ? policyErr : "daemon request failed");
            return 1;
        }
        printf("Startup policy: %s\n",
               service_startup_policy_mode_name(policy.state.startupPolicyMode));
        if (policy.state.startupPolicyMode == SERVICE_STARTUP_POLICY_PROFILE)
            printf("Startup profile slot: %u\n",
                   (unsigned int)policy.state.startupPolicySlot);
        if (policy.message[0]) printf("%s\n", policy.message);
        // "What boots" is the snapshot the daemon holds, not the profile as it
        // reads today; say so whenever the two have drifted apart.
        LinuxStartupSnapshotReport report = linux_startup_snapshot_report(
            configPath, true, policy.state.startupPolicyMode,
            policy.state.startupPolicySlot);
        print_startup_snapshot_report(stdout, &report, configPath);
    }

    if (opts.startupPolicyAction == LINUX_STARTUP_POLICY_ACTION_SET) {
        char policyResult[512] = {};
        bool policyOk = false;
        if (opts.startupPolicyMode == SERVICE_STARTUP_POLICY_PROFILE) {
            // The daemon cannot read the caller's config.ini (ProtectHome=yes),
            // so the profile is resolved here and stored as a snapshot bound to
            // one exact GPU identity.
            DesiredSettings startupDesired = {};
            char loadErr[256] = {};
            if (!load_profile_from_config_path(configPath, opts.startupPolicySlot,
                                               &startupDesired, loadErr,
                                               sizeof(loadErr))) {
                fprintf(stderr, "Cannot load profile %d for the startup policy: %s\n",
                        opts.startupPolicySlot,
                        loadErr[0] ? loadErr : "profile unavailable");
                return 1;
            }
            normalize_desired_settings_for_ui(&startupDesired);
            GpuAdapterInfo startupTarget = {};
            char targetErr[256] = {};
            if (!linux_daemon_resolve_write_target(
                    gpuTarget.valid ? &gpuTarget : nullptr, &startupTarget,
                    targetErr, sizeof(targetErr))) {
                fprintf(stderr, "Cannot bind the startup policy to a GPU: %s\n",
                        targetErr[0] ? targetErr : "no exact GPU identity");
                return 1;
            }
            char label[64] = {};
            snprintf(label, sizeof(label), "profile %d", opts.startupPolicySlot);
            policyOk = linux_daemon_set_startup_policy(
                SERVICE_STARTUP_POLICY_PROFILE, opts.startupPolicySlot, label,
                &startupTarget, &startupDesired,
                policyResult, sizeof(policyResult));
        } else {
            policyOk = linux_daemon_set_startup_policy(
                (unsigned int)opts.startupPolicyMode, 0, nullptr, nullptr,
                nullptr, policyResult, sizeof(policyResult));
        }
        printf("%s\n", policyResult[0] ? policyResult
                                       : (policyOk ? "Startup policy updated"
                                                   : "Startup policy update failed"));
        if (!policyOk) return 1;
    }

    if (opts.dump) {
        print_desired_settings_text(stdout, slot, &desired);
    }

    if (opts.json) {
        print_desired_settings_json(stdout, slot, &desired);
    }

    if (opts.applyConfig) {
        char result[512] = {};
        bool ok;
        if (opts.reset && !opts.hasProfileSlot) {
            // `--reset --apply-config` releases OC/UV to driver defaults.
            ok = linux_daemon_reset(gpuTarget.valid ? &gpuTarget : nullptr, result, sizeof(result));
        } else {
            ok = linux_daemon_apply(gpuTarget.valid ? &gpuTarget : nullptr,
                                    &desired, true, result, sizeof(result));
        }
        printf("%s\n", result[0] ? result : (ok ? "Applied" : "Apply failed"));
        if (!ok) return 1;
    }

    if (opts.showHelp || opts.dump || opts.json || opts.dumpLive || opts.jsonLive ||
        opts.probe || opts.writeAssets || opts.saveConfig || opts.applyConfig ||
        opts.startupPolicyAction != LINUX_STARTUP_POLICY_ACTION_NONE) {
        return 0;
    }

    // Started by double-clicking the binary in a file manager: there is no
    // terminal to draw the TUI in, so re-exec inside the session's terminal
    // emulator rather than failing to a stderr nobody can see.
    if (linux_terminal_relaunch_wanted(opts.fromDesktop)) {
        char relaunchErr[512] = {};
        linux_terminal_relaunch(argc, argv, relaunchErr, sizeof(relaunchErr));
        // Only reached when no terminal could be started; the message is the
        // actionable one (which terminals were looked for, and what to run).
        fprintf(stderr, "%s\n", relaunchErr[0] ? relaunchErr
            : "cannot open a terminal window for the Green Curve TUI");
        return 1;
    }

    // The TUI starts from the daemon's live state.  A selected profile is only
    // staged after the user explicitly activates Load inside the TUI.
    int tuiStatus = linux_run_tui(configPath, slot, nullptr,
                                  gpuTarget.valid ? &gpuTarget : nullptr);
    linux_debug_logf("tui: exited with status %d fromDesktop=%d",
                     tuiStatus, opts.fromDesktop ? 1 : 0);
    if (opts.fromDesktop && tuiStatus != 0) {
        // The terminal window closes as soon as this process exits, which is
        // what the user wants after pressing q — but it would also erase the
        // reason for a failure before it could be read.
        fprintf(stderr, "\nGreen Curve exited with status %d. "
                        "Press Enter to close this window.\n", tuiStatus);
        int discarded = 0;
        while ((discarded = getchar()) != '\n' && discarded != EOF) {}
    }
    return tuiStatus;
}
