// SPDX-FileCopyrightText: Copyright (c) 2026 aufkrawall
// SPDX-License-Identifier: MIT
//
// The updater's trust root: the ECDSA P-256 public keys that a release
// manifest's signature must verify against.
//
// These are PUBLIC keys and belong in the repository.  Their private halves
// live offline on the maintainer's machine and never enter GitHub Actions,
// which is the entire point of the design: the GitHub build-provenance
// attestation proves "CI built this from repo X at commit Y", so a compromised
// account can mint a valid attestation for hostile code simply by pushing a
// commit and running the release workflow.  A key GitHub has never held cannot
// be used that way, so it -- not the attestation and not the published
// `.sha256` files -- is what actually gates running a downloaded installer as
// SYSTEM.
//
// ## Format
//
// 64 bytes: the X coordinate followed by the Y coordinate, big-endian, 32
// bytes each.  This is exactly the tail of a `BCRYPT_ECCKEY_BLOB`, so the
// verifier can prepend a fixed header and hand the result straight to CNG
// without a DER or SEC1 decoder in the path.
//
// ## Two slots, from the first release that has an updater at all
//
// `ACTIVE` signs today's releases.  `NEXT` is a pre-published rollover key
// whose private half is stored separately.  Both are accepted, so a key can be
// retired without stranding every installed copy on a version it can no longer
// verify -- which, for an updater, is unrecoverable except by asking every user
// to reinstall by hand.
//
// Rotating:
//   1. Start signing manifests with the NEXT key.
//   2. Ship a build that moves NEXT into ACTIVE and introduces a fresh NEXT.
//   3. Only once that build is broadly deployed, stop accepting the old ACTIVE.
//
// Step 3 is the one that must not be rushed: removing a key is what breaks
// clients, and a client that cannot verify cannot update itself out of the
// problem.
//
// Generated by `python tools/update_signing.py gen-key <path>`.

#ifndef GREEN_CURVE_UPDATE_VERIFY_KEYS_H
#define GREEN_CURVE_UPDATE_VERIFY_KEYS_H

#include <stddef.h>

#define GC_UPDATE_PUBLIC_KEY_BYTES 64
#define GC_UPDATE_SIGNATURE_BYTES 64

// The Add/Remove Programs key the installer writes, which is where the updater
// reads InstallLocation from to answer "is this an installed copy, and which
// directory does it upgrade".
//
// This is a SECOND spelling of `GC_SETUP_UNINSTALL_KEY` in installer_common.h,
// and that duplication is deliberate: installer.md invariant 11 keeps setup and
// the application model strictly apart, so neither may include the other's
// header. A silent disagreement between the two would make the updater decide
// every installation is a portable copy -- it would simply stop offering
// updates, with nothing failing anywhere. `check_all()` in build.py asserts the
// two literals are identical, exactly as it does for the setup icon id, which
// is the same failure shape.
#define GC_UPDATE_UNINSTALL_KEY \
    L"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Green Curve"

// Active release-signing key.
static const unsigned char GC_UPDATE_PUBLIC_KEY_ACTIVE[GC_UPDATE_PUBLIC_KEY_BYTES] = {
    0xA2, 0x8B, 0xA6, 0xC2, 0xE8, 0xD5, 0xD9, 0x90,
    0x60, 0x2D, 0x2A, 0x6E, 0x8A, 0x0D, 0x9B, 0xEC,
    0x80, 0xC8, 0x7B, 0x6D, 0xD1, 0x3F, 0xEE, 0x82,
    0x76, 0x2B, 0x2B, 0x19, 0x9E, 0xC7, 0xD2, 0x20,
    0xC1, 0x12, 0x10, 0xF3, 0x8A, 0x68, 0x63, 0xD8,
    0xDD, 0xEF, 0x70, 0x4C, 0x88, 0xB0, 0x14, 0x52,
    0x1B, 0x15, 0xFB, 0xB7, 0x59, 0x40, 0x89, 0xB5,
    0xBC, 0x77, 0x3B, 0x25, 0x3F, 0xF2, 0x00, 0xD8,
};

// Pre-published rollover key.  Not yet used for signing.
static const unsigned char GC_UPDATE_PUBLIC_KEY_NEXT[GC_UPDATE_PUBLIC_KEY_BYTES] = {
    0x9A, 0xC3, 0xB5, 0x14, 0xCA, 0x9F, 0x5B, 0xE4,
    0xB8, 0xB5, 0xF1, 0xBD, 0x87, 0x11, 0xE1, 0xB9,
    0xD0, 0x12, 0x44, 0x1E, 0x6F, 0x44, 0x9F, 0x5A,
    0x11, 0x19, 0x31, 0xD1, 0x24, 0x30, 0xDE, 0x5E,
    0xDE, 0xC7, 0xB0, 0xBC, 0x64, 0x88, 0x84, 0xC1,
    0xED, 0xFB, 0x61, 0xEB, 0xD6, 0x13, 0x34, 0xF9,
    0xC5, 0xB3, 0xAD, 0x48, 0x3C, 0xD3, 0xEC, 0xCB,
    0x25, 0xFC, 0x44, 0x61, 0xD7, 0xA4, 0xF9, 0xE5,
};

// Every key a manifest signature may verify against.  Order is not significant;
// a signature is accepted when ANY entry verifies it.
static const unsigned char* const GC_UPDATE_PUBLIC_KEYS[] = {
    GC_UPDATE_PUBLIC_KEY_ACTIVE,
    GC_UPDATE_PUBLIC_KEY_NEXT,
};

#define GC_UPDATE_PUBLIC_KEY_COUNT \
    (sizeof(GC_UPDATE_PUBLIC_KEYS) / sizeof(GC_UPDATE_PUBLIC_KEYS[0]))

// A key slot that was never filled in would be all zeros, and an all-zero
// "public key" is not a point on P-256 -- CNG rejects it -- but it would fail
// as an import error rather than as an obviously wrong configuration.  This
// predicate lets the verifier say which of the two happened.
static inline bool gc_update_key_is_populated(const unsigned char* key) {
    if (!key) return false;
    for (size_t i = 0; i < GC_UPDATE_PUBLIC_KEY_BYTES; ++i) {
        if (key[i] != 0) return true;
    }
    return false;
}

#endif // GREEN_CURVE_UPDATE_VERIFY_KEYS_H
